"""Render a self-contained context file from declaration signatures."""

from __future__ import annotations

from ..common import module_short
from .tracker import DeclInfo, display_name


def _short_parent_name(fqn: str) -> str:
    """Extract short name from a fully qualified parent name.

    E.g., 'Quantum.Operators.PosSemidefOp' -> 'PosSemidefOp'
    """
    return fqn.rsplit(".", 1)[-1]


def render_decl(decl: DeclInfo, short_name: bool = False, include_docstrings: bool = True) -> str:
    """Render a single declaration as pseudo-Lean."""
    # Always use display_name for private decls (strips _private. prefix)
    name = display_name(decl) if (short_name or decl.is_private) else decl.name
    lines: list[str] = []

    # Sorry warning
    if decl.has_sorry:
        lines.append(f"-- WARNING: contains sorry")

    # Docstring
    if include_docstrings and decl.docstring:
        doc = decl.docstring.rstrip()
        if "\n" in doc:
            lines.append("/--")
            for doc_line in doc.split("\n"):
                lines.append(f"  {doc_line}")
            lines.append("-/")
        else:
            lines.append(f"/-- {doc} -/")

    if decl.fields:
        # Structure/class with fields -- show type signature for parameters
        sig = decl.type_signature
        kind_word = decl.kind if decl.kind in ("structure", "class") else "structure"

        # Build header
        header = f"{kind_word} {name}"
        if sig and sig != "Type" and sig != "Prop":
            header += f" : {sig}"

        # Add extends clause if structure has parents
        if decl.parents:
            parent_names = [_short_parent_name(p) for p in decl.parents]
            header += f" extends {', '.join(parent_names)}"

        header += " where"
        lines.append(header)

        # Only show non-parent (declared) fields
        for f in decl.fields:
            if not f.from_parent:
                lines.append(f"  {f.name} : {f.type}")

    elif decl.constructors:
        # Show type signature on first line, then constructors
        lines.append(f"inductive {name} :")
        lines.append(f"  {decl.type_signature}")
        for c in decl.constructors:
            lines.append(f"  | {c.name} : {c.type}")

    elif decl.kind == "abbrev" and decl.value:
        lines.append(f"abbrev {name} : {decl.type_signature} :=")
        lines.append(f"  {decl.value}")

    elif decl.kind in ("def", "instance") and decl.value:
        lines.append(f"{decl.kind} {name} : {decl.type_signature} :=")
        lines.append(f"  {decl.value}")

    else:
        # theorem, axiom, opaque, or def/instance without value -- just show type
        lines.append(f"{decl.kind} {name} :")
        lines.append(f"  {decl.type_signature}")

    return "\n".join(lines)


def _projection_names(decls: list[DeclInfo]) -> set[str]:
    """Collect all structure field projection names from a list of declarations.

    Used to filter out standalone projection declarations (abbrevs/theorems)
    that duplicate information already shown in the structure definition.
    """
    proj_names: set[str] = set()
    for d in decls:
        if d.fields:
            for f in d.fields:
                if f.proj_name:
                    proj_names.add(f.proj_name)
    return proj_names


def render_context(
    targets: list[DeclInfo],
    context: list[DeclInfo],
    root_module: str = "",
    header: str = "",
    include_docstrings: bool = True,
) -> str:
    """Render the full context file.

    Args:
        targets: Declarations under audit (shown first).
        context: All other declarations in the closure (shown after).
        root_module: For shortening module paths in section headers.
        header: Optional header text (e.g., file path).
    """
    lines: list[str] = []

    # Header
    lines.append("-- " + "=" * 62)
    if header:
        lines.append(f"-- Context for: {header}")
    lines.append("-- Generated by sig-graph")
    lines.append("-- " + "=" * 62)
    lines.append("")

    # Target declarations
    target_names = {d.name for d in targets}

    if targets:
        lines.append("-- " + "\u2500" * 20 + " Target declarations (under audit) " + "\u2500" * 20)
        lines.append("")
        for decl in targets:
            lines.append(render_decl(decl, include_docstrings=include_docstrings))
            lines.append("")

    # Context declarations, grouped by module
    if context:
        ctx_only = [d for d in context if d.name not in target_names]

        # Filter out standalone projections that duplicate structure field info
        all_decls = list(targets) + ctx_only
        proj_names = _projection_names(all_decls)
        ctx_only = [d for d in ctx_only if d.name not in proj_names]

        # Topological sort: leaf dependencies first (most fundamental types first)
        # Build a dependency graph restricted to ctx_only names
        ctx_names = {d.name for d in ctx_only}
        ctx_by_name = {d.name: d for d in ctx_only}
        # Count how many ctx deps each decl has (in-degree within ctx)
        in_degree = {d.name: 0 for d in ctx_only}
        for d in ctx_only:
            for dep in d.deps:
                if dep in ctx_names and dep != d.name:
                    in_degree[d.name] = in_degree.get(d.name, 0) + 1
        # Kahn's algorithm: start with leaves (in_degree == 0)
        from collections import deque
        queue = deque(n for n, deg in in_degree.items() if deg == 0)
        sorted_names: list[str] = []
        while queue:
            name = queue.popleft()
            sorted_names.append(name)
            # Find decls that depend on this one and decrement their in-degree
            for d in ctx_only:
                if name in d.deps and d.name in in_degree:
                    in_degree[d.name] -= 1
                    if in_degree[d.name] == 0:
                        queue.append(d.name)
        # Add any remaining (cycles or disconnected) in original reversed order
        remaining = [d.name for d in reversed(ctx_only) if d.name not in set(sorted_names)]
        sorted_names.extend(remaining)
        ctx_only = [ctx_by_name[n] for n in sorted_names]

        if ctx_only:
            # Group by module, preserving reversed (leaf-first) order
            by_module: dict[str, list[DeclInfo]] = {}
            module_order: list[str] = []
            for d in ctx_only:
                if d.module not in by_module:
                    module_order.append(d.module)
                by_module.setdefault(d.module, []).append(d)

            lines.append("-- " + "\u2500" * 20 + " Required context " + "\u2500" * 25)
            lines.append("-- (project-local types referenced by targets, recursively)")
            lines.append("")

            for mod in module_order:
                mod_display = module_short(mod, root_module)
                lines.append(f"-- From {mod_display}")
                lines.append("")
                for decl in by_module[mod]:
                    lines.append(render_decl(decl, include_docstrings=include_docstrings))
                    lines.append("")

    return "\n".join(lines)
