/-
  Export all project declarations with their type signatures, fields,
  and constructors as JSON.

  Usage:
    lake build  -- must build first
    lake env lean --run <path>/ExportSigs.lean <RootModule>

  Output: JSON with declaration name, kind, module, pretty-printed type
  signature, type-level dependencies, structure fields, and inductive
  constructors.

  Only follows project-local dependencies. External library declarations
  (Mathlib/Init/Std) are excluded from deps.

  Auto-generated sub-declarations are skipped from rendered signature context;
  duplicate declarations observed through multiple modules are emitted once.
-/
import Lean

open Lean Meta

/-- Classify a constant into a user-facing kind, or `none` for internal things. -/
def getKind (ci : ConstantInfo) : Option String := match ci with
  | .ctorInfo _  => none
  | .recInfo _   => none
  | .quotInfo _  => none
  | .defnInfo _  => some "def"
  | .thmInfo _   => some "theorem"
  | .axiomInfo _  => some "axiom"
  | .inductInfo _ => some "inductive"
  | .opaqueInfo _ => some "opaque"

/-- Get constants referenced only in the TYPE of a declaration. -/
def getTypeConstants (ci : ConstantInfo) : Array Name :=
  ci.type.getUsedConstants

/-- Get constants referenced in the VALUE of a declaration. -/
def getValueConstants (ci : ConstantInfo) : Array Name := match ci with
  | .defnInfo v  => v.value.getUsedConstants
  | .thmInfo v   => v.value.getUsedConstants
  | .opaqueInfo v => v.value.getUsedConstants
  | _ => #[]

/-- Get all constants (type + value). -/
def getAllConstants (ci : ConstantInfo) : Array Name :=
  getTypeConstants ci ++ getValueConstants ci

/-- Find the parent name for a sub-declaration by stripping the last component. -/
def findParent (name : Name) (projectNames : NameHashSet) : Option Name :=
  match name with
  | .str parent _ =>
    if projectNames.contains parent then some parent else none
  | _ => none

/-- Check if a name looks like a compiler-generated proof sub-declaration
    (e.g., `Foo.bar._proof_1`, `Foo.bar._uniq.123`). -/
def isProofSubDecl (name : Name) : Bool :=
  match name with
  | .str _ s => s.startsWith "_proof_" || s.startsWith "_uniq."
  | .num (.str _ s) _ => s == "_uniq"
  | _ => false

/-- Auto-generated boilerplate suffixes that Lean creates for structures/inductives.
    These are not useful for auditors. -/
private def autoGenSuffixes : Array String :=
  #["noConfusion", "noConfusionType", "recOn", "casesOn", "ctorIdx",
    "brecOn", "sizeOf_spec", "congr_simp"]

/-- Check if a name is auto-generated boilerplate for a structure/inductive.
    E.g., `Foo.Bar.noConfusion`, `Foo.Bar.mk.injEq`, `Foo.Bar.mk.sizeOf_spec`. -/
def isAutoGenerated (name : Name) (projectNames : NameHashSet) : Bool :=
  match name with
  | .str parent s =>
    -- Direct suffix match (e.g., Foo.Bar.noConfusion)
    if autoGenSuffixes.contains s then true
    -- .mk sub-declarations (e.g., Foo.Bar.mk.injEq, Foo.Bar.mk.inj)
    else match parent with
    | .str grandparent "mk" => projectNames.contains grandparent
    | _ => false
  | _ => false

/-- Get the head constant name from an expression, stripping applications
    and projections. E.g., `(eigenvaluesOf_spec ρ).2.2.2` → `eigenvaluesOf_spec`. -/
partial def getHeadConst : Expr → Option Name
  | .app f _ => getHeadConst f
  | .proj _ _ e => getHeadConst e
  | .const n _ => some n
  | .mdata _ e => getHeadConst e
  | _ => none

/-- Get the head function constant from an application spine.
    `f a1 a2 ... aN` → `f` (if `f` is a const). Strips projections too. -/
partial def getAppHeadConst : Expr → Option Name
  | .app f _ => getAppHeadConst f
  | .const n _ => some n
  | .mdata _ e => getAppHeadConst e
  | .proj _ _ e => getAppHeadConst e
  | _ => none

/-- Collect all constant names from an expression, recursively.
    Uses fuel to avoid blowup on large expressions. -/
partial def collectAllConsts (e : Expr) (fuel : Nat := 50) : Array Name :=
  if fuel == 0 then #[]
  else match e with
    | .const n _ => #[n]
    | .app f a => collectAllConsts f (fuel - 1) ++ collectAllConsts a (fuel - 1)
    | .proj _ _ inner => collectAllConsts inner (fuel - 1)
    | .lam _ t b _ => collectAllConsts t (fuel - 1) ++ collectAllConsts b (fuel - 1)
    | .forallE _ t b _ => collectAllConsts t (fuel - 1) ++ collectAllConsts b (fuel - 1)
    | .letE _ t v b _ => collectAllConsts t (fuel - 1) ++ collectAllConsts v (fuel - 1)
                          ++ collectAllConsts b (fuel - 1)
    | .mdata _ inner => collectAllConsts inner (fuel - 1)
    | _ => #[]

/-- Resolve a `_proof_N` sub-declaration to the most informative
    constant in its value. Returns `none` if resolution fails. -/
def resolveProofSubDecl (env : Environment) (name : Name)
    (projectNames : NameHashSet) : Option Name := do
  if !isProofSubDecl name then failure
  let ci ← env.find? name
  let val ← match ci with
    | .thmInfo v => some v.value
    | .defnInfo v => some v.value
    | _ => none
  -- Strip lambdas to get to the body
  let mut e := val
  while e.isLambda do
    e := e.bindingBody!
  let consts := collectAllConsts e
  -- Prefer project-local, non-internal, non-proof-subdecl names
  for c in consts do
    if projectNames.contains c && c != name && !isProofSubDecl c && !c.isInternal then
      return c
  failure

/-- Replace references to `_proof_N` sub-declarations with the resolved head constant
    in an expression. This makes pretty-printed output show the original theorem names. -/
partial def resolveProofRefs (env : Environment) (projectNames : NameHashSet)
    (e : Expr) : Expr :=
  match e with
  | .const n ls =>
    match resolveProofSubDecl env n projectNames with
    | some resolved => .const resolved ls
    | none => e
  | .app f a => .app (resolveProofRefs env projectNames f)
                     (resolveProofRefs env projectNames a)
  | .lam n t b bi => .lam n (resolveProofRefs env projectNames t)
                            (resolveProofRefs env projectNames b) bi
  | .forallE n t b bi => .forallE n (resolveProofRefs env projectNames t)
                                    (resolveProofRefs env projectNames b) bi
  | .letE n t v b nd => .letE n (resolveProofRefs env projectNames t)
                                (resolveProofRefs env projectNames v)
                                (resolveProofRefs env projectNames b) nd
  | .mdata m e => .mdata m (resolveProofRefs env projectNames e)
  | .proj t i e => .proj t i (resolveProofRefs env projectNames e)
  | _ => e

/-- Run a MetaM action in IO with the given environment. -/
def runMetaIO (env : Environment) (action : MetaM α) : IO (Except Exception α) := do
  let opts := ({} : Options)
    |>.setBool `pp.fieldNotation true
    |>.setBool `pp.fullNames false
    |>.setBool `pp.proofs false
    |>.setBool `pp.universes false
    |>.setBool `pp.instanceNames false
    |>.setBool `pp.all false
    |>.setBool `pp.raw false
  let coreCtx : Core.Context := {
    options := opts
    fileName := "<export>"
    fileMap := FileMap.ofString ""
  }
  let coreState : Core.State := { env := env }
  (action.run' {} {} |>.run' coreCtx coreState).toIO'

/-- Run a MetaM action in IO with the given environment and a set of open namespaces.
    Opening the declaration's own namespace chain allows pp.fullNames=false to shorten
    sibling references (e.g. `Foo.Bar.Baz` → `Baz` when `Foo.Bar` is open). -/
def runMetaIOWithOpenDecls (env : Environment) (openDecls : List OpenDecl)
    (action : MetaM α) : IO (Except Exception α) := do
  let opts := ({} : Options)
    |>.setBool `pp.fieldNotation true
    |>.setBool `pp.fullNames false
    |>.setBool `pp.proofs false
    |>.setBool `pp.universes false
    |>.setBool `pp.instanceNames false
    |>.setBool `pp.all false
    |>.setBool `pp.raw false
  let coreCtx : Core.Context := {
    options := opts
    fileName := "<export>"
    fileMap := FileMap.ofString ""
    openDecls := openDecls
  }
  let coreState : Core.State := { env := env }
  (action.run' {} {} |>.run' coreCtx coreState).toIO'

/-- Build the list of OpenDecl entries for all namespace prefixes of a declaration name.
    For `A.B.C.myDef` this opens `A`, `A.B`, and `A.B.C`, matching what Lean does when
    the declaration is written inside `namespace A.B.C`. Skips `.anonymous`. -/
def namespacesOf (declName : Name) : List OpenDecl :=
  let rec go (n : Name) (acc : List OpenDecl) : List OpenDecl :=
    match n with
    | .anonymous => acc
    | .str .anonymous _ => acc  -- top-level name; no namespace to open
    | .str parent _ => go parent (.simple parent [] :: acc)
    | .num parent _ => go parent acc
  go declName []

/-- Pretty-print an expression using Lean's formatter. -/
def ppExprStr (env : Environment) (e : Expr) : IO String := do
  match ← runMetaIO env (do return (← ppExpr e).pretty (width := 120)) with
  | .ok result => return result
  | .error e => return s!"<pp error: {← e.toMessageData.toString}>"

/-- Pretty-print an expression with the declaration's own namespace chain opened,
    plus any additional open decls (e.g., project-wide namespaces).
    This shortens references to siblings and cross-module project types. -/
def ppExprStrIn (env : Environment) (declName : Name) (e : Expr)
    (extraOpenDecls : List OpenDecl := []) : IO String := do
  let opens := namespacesOf declName ++ extraOpenDecls
  match ← runMetaIOWithOpenDecls env opens (do return (← ppExpr e).pretty (width := 120)) with
  | .ok result => return result
  | .error e => return s!"<pp error: {← e.toMessageData.toString}>"

/-- Check if a constant name transitively contains `sorryAx` in its value,
    following `_proof_N` sub-declaration references. -/
partial def isSorryTaintedConst (env : Environment) (name : Name) : Bool :=
  go name {}  |>.2
where
  go (name : Name) (visited : NameHashSet) : NameHashSet × Bool :=
    if visited.contains name then (visited, false)
    else
      let visited := visited.insert name
      match env.find? name with
      | none => (visited, false)
      | some ci =>
        let val? := match ci with
          | .thmInfo v => some v.value
          | .defnInfo v => some v.value
          | .opaqueInfo v => some v.value
          | _ => none
        match val? with
        | none => (visited, false)
        | some val =>
          if val.getUsedConstants.any (· == ``sorryAx) then (visited, true)
          else
            let subProofs := val.getUsedConstants.filter fun n =>
              match n with
              | .str _ s => s.startsWith "_proof_" || s.startsWith "_uniq."
              | _ => false
            subProofs.foldl (init := (visited, false)) fun (vis, found) sp =>
              if found then (vis, true)
              else go sp vis

/-- Compute the set of constant names referenced by `root` that transitively
    contain `sorryAx`. Only checks `_proof_N` / `_uniq` sub-declarations. -/
def computeSorryTainted (env : Environment) (root : Expr) : NameHashSet :=
  let directRefs := root.getUsedConstants
  let candidates := directRefs.filter fun n =>
    match n with
    | .str _ s => s.startsWith "_proof_" || s.startsWith "_uniq."
    | _ => false
  candidates.foldl (init := {}) fun tainted c =>
    if isSorryTaintedConst env c then tainted.insert c else tainted

/-- Check if a declaration's value transitively contains `sorryAx`,
    following `_proof_N` references. -/
def hasSorryTransitiveCheck (env : Environment) (ci : ConstantInfo) : Bool :=
  let val? := match ci with
    | .thmInfo v => some v.value
    | .defnInfo v => some v.value
    | .opaqueInfo v => some v.value
    | _ => none
  match val? with
  | none => false
  | some val =>
    if val.getUsedConstants.any (· == ``sorryAx) then true
    else !(computeSorryTainted env val).isEmpty

/-- Erase Prop-typed subexpressions in a value, replacing them with `⋯`.
    This hides proof terms while preserving computational content.
    Works on the Expr level before pretty-printing.

    Key design: when erasing a Prop-typed argument, we don't replace it
    entirely with sorry. Instead we "shallow erase": preserve the head
    constant/theorem name but erase ITS Prop-typed arguments. This way
    `Classical.choose (exists_unique_threshold h1 h2)` becomes
    `Classical.choose (exists_unique_threshold ⋯ ⋯)` rather than
    `Classical.choose ⋯`, keeping the semantic link to the theorem name.

    When a Prop-typed expression's head constant is in the sorry-tainted set,
    we replace the entire expression with `sorryAx` so that `pp.proofs false`
    renders it as `sorry`. -/
partial def erasePropSubexprs (env : Environment) (e : Expr)
    (sorryTainted : NameHashSet := {}) : IO Expr := do
  match ← runMetaIO env (erasePropsM e) with
  | .ok result => return result
  | .error _ => return e  -- fallback: return original
where
  /-- Check if any constant in the expression is in the sorry-tainted set. -/
  containsSorryTainted (e : Expr) : Bool :=
    e.getUsedConstants.any sorryTainted.contains

  /-- Shallow-erase a Prop-typed expression: keep its head constant name
      but replace all its Prop-typed arguments with ⋯.
      Non-Prop arguments are kept as-is (they carry type info).
      If any constant is sorry-tainted, replace the whole thing with sorryAx
      so pp renders it as `sorry`. -/
  shallowEraseProp (e : Expr) : MetaM Expr := do
    if containsSorryTainted e then
      return mkConst ``sorryAx
    match e with
    | .app f a =>
      let f' ← shallowEraseProp f
      let aType? ← try some <$> inferType a catch _ => pure none
      match aType? with
      | some aType =>
        let isPropArg ← try isProp aType catch _ => pure false
        if isPropArg then
          return .app f' (.const `«⋯» [])
        else
          return .app f' a
      | none => return .app f' a
    | .proj typeName idx struct =>
      -- Preserve projections — recurse into the struct to keep its head name
      let struct' ← shallowEraseProp struct
      return .proj typeName idx struct'
    | .mdata m e => return .mdata m (← shallowEraseProp e)
    | _ => return e  -- base case: keep constants, vars, etc.

  erasePropsM (e : Expr) : MetaM Expr := do
    -- Top-level check: if the entire expression is Prop-typed, replace with ⋯
    let eType? ← try some <$> inferType e catch _ => pure none
    match eType? with
    | some eType =>
      let isFullyProp ← try isProp eType catch _ => pure false
      if isFullyProp then
        return .const `«⋯» []
    | none => pure ()
    match e with
    | .lam n t b bi =>
      let t' ← erasePropsM t
      let b' ← withLocalDecl n bi t' fun x => do
        let b' ← erasePropsM (b.instantiate1 x)
        mkLambdaFVars #[x] b'
      return b'
    | .forallE n t b bi =>
      let t' ← erasePropsM t
      let b' ← withLocalDecl n bi t' fun x => do
        let b' ← erasePropsM (b.instantiate1 x)
        mkForallFVars #[x] b'
      return b'
    | .letE n t v b _ =>
      let isProp ← try isProp t catch _ => pure false
      if isProp then
        return .letE n t (.const `«⋯» []) b true
      else
        let t' ← erasePropsM t
        let v' ← erasePropsM v
        let b' ← withLetDecl n t' v' fun x => do
          let b' ← erasePropsM (b.instantiate1 x)
          mkLetFVars #[x] b'
        return b'
    | .app f a =>
      let aType? ← try some <$> inferType a catch _ => pure none
      match aType? with
      | some aType =>
        let isPropArg ← try isProp aType catch _ => pure false
        if isPropArg then
          let f' ← erasePropsM f
          return .app f' (.const `«⋯» [])
        else
          let f' ← erasePropsM f
          let a' ← erasePropsM a
          return .app f' a'
      | none =>
        let f' ← erasePropsM f
        let a' ← erasePropsM a
        return .app f' a'
    | .mdata m e => return .mdata m (← erasePropsM e)
    | .proj t i e => return .proj t i (← erasePropsM e)
    | _ => return e

/-- Get constants from an expression, excluding those inside Prop-typed subexprs,
    with _proof_N references resolved to original theorem names. -/
def getNonPropConstants (env : Environment) (projectNames : NameHashSet)
    (e : Expr) : IO (Array Name) := do
  let tainted := computeSorryTainted env e
  let erased ← erasePropSubexprs env e tainted
  let resolved := resolveProofRefs env projectNames erased
  return resolved.getUsedConstants

/-- Replace all applications of `_proof_N` sub-declarations with `⋯`.
    These are proof terms extracted by the kernel; their pp output is
    always noise (and often garbled when `pp.proofs false` fails on them). -/
partial def eraseProofSubDeclApps (e : Expr) : Expr :=
  match e with
  | .app f a =>
    -- Check if the head of this application chain is a _proof_N constant
    let head := e.getAppFn
    match head with
    | .const n _ =>
      if isProofSubDecl n then .const `«⋯» []
      else .app (eraseProofSubDeclApps f) (eraseProofSubDeclApps a)
    | _ => .app (eraseProofSubDeclApps f) (eraseProofSubDeclApps a)
  | .lam n t b bi => .lam n (eraseProofSubDeclApps t) (eraseProofSubDeclApps b) bi
  | .forallE n t b bi => .forallE n (eraseProofSubDeclApps t) (eraseProofSubDeclApps b) bi
  | .letE n t v b nd => .letE n (eraseProofSubDeclApps t) (eraseProofSubDeclApps v) (eraseProofSubDeclApps b) nd
  | .mdata m e => .mdata m (eraseProofSubDeclApps e)
  | .proj t i e => .proj t i (eraseProofSubDeclApps e)
  | .const n _ls => if isProofSubDecl n then .const `«⋯» [] else e
  | _ => e

def ppValueStr (env : Environment) (projectNames : NameHashSet) (declName : Name)
    (e : Expr) (extraOpenDecls : List OpenDecl := []) : IO String := do
  let tainted := computeSorryTainted env e
  let cleaned := eraseProofSubDeclApps e
  let erased ← erasePropSubexprs env cleaned tainted
  let resolved := resolveProofRefs env projectNames erased
  ppExprStrIn env declName resolved extraOpenDecls

/-- Pretty-print the field type from a projection function type.
    Strips exactly `numToStrip` leading ∀/Π binders (structure type params + self)
    using forallBoundedTelescope, preserving remaining binders (e.g., ∀ x, ...).
    Opens the structure's namespace chain for shorter sibling references. -/
def ppFieldType (env : Environment) (structName : Name) (numToStrip : Nat)
    (projType : Expr) (extraOpenDecls : List OpenDecl := []) : IO String := do
  let opens := namespacesOf structName ++ extraOpenDecls
  match ← runMetaIOWithOpenDecls env opens (do
    forallBoundedTelescope projType (some numToStrip) fun _ body => do
      return (← ppExpr body).pretty (width := 120)
  ) with
  | .ok result => return result
  | .error _ => ppExprStrIn env structName projType extraOpenDecls  -- fallback to full type

/-- Get structure field info as JSON array. Returns `none` for non-structures.
    Iterates `fieldNames` (declaration order) rather than `fieldInfo` (alphabetical). -/
def getStructureFields (env : Environment) (name : Name)
    (extraOpenDecls : List OpenDecl := []) : IO (Option (Array Json)) := do
  let some info := getStructureInfo? env name | return none
  -- Get numParams from the inductive type — strip these + 1 (self) from projection types
  let numParams := match env.find? name with
    | some (.inductInfo val) => val.numParams
    | _ => 0
  let numToStrip := numParams + 1
  let mut fields : Array Json := #[]
  -- Iterate fieldNames (position order, not alphabetical fieldInfo order)
  for fieldName in info.fieldNames do
    let projName := name ++ fieldName
    let some projInfo := env.find? projName | continue
    -- Look up metadata for fromParent check
    let fromParent := match info.fieldInfo.find? (fun fi => fi.fieldName == fieldName) with
      | some fi => fi.subobject?.isSome
      | none => false
    -- Strip only structure params + self, preserving field-level binders
    let typeStr ← ppFieldType env name numToStrip projInfo.type extraOpenDecls
    fields := fields.push <| Json.mkObj [
      ("name", .str fieldName.toString),
      ("type", .str typeStr),
      ("projName", .str projName.toString),
      ("fromParent", .bool fromParent)
    ]
  return some fields

/-- Get parent structure names for structures using `extends`. Returns `none` for non-structures
    or structures with no parents. -/
def getStructureParentNames (env : Environment) (name : Name) : Option (Array Json) :=
  match getStructureInfo? env name with
  | some info =>
    if info.parentInfo.isEmpty then none
    else some (info.parentInfo.map fun p => Json.str p.structName.toString)
  | none => none

/-- Get inductive constructor info as JSON array. -/
def getConstructors (env : Environment) (name : Name)
    (extraOpenDecls : List OpenDecl := []) : IO (Option (Array Json)) := do
  let some indInfo := env.find? name | return none
  let .inductInfo val := indInfo | return none
  let mut ctors : Array Json := #[]
  for ctorName in val.ctors do
    let some ctorInfo := env.find? ctorName | continue
    -- Open the inductive's namespace so constructor types show short sibling names
    let typeStr ← ppExprStrIn env name ctorInfo.type extraOpenDecls
    ctors := ctors.push <| Json.mkObj [
      ("name", .str (ctorName.getString!)),
      ("type", .str typeStr)
    ]
  return some ctors

/-- Get field-level type dependencies for structures (constants in field types). -/
def getFieldTypeDeps (env : Environment) (name : Name) : Array Name :=
  match getStructureInfo? env name with
  | none => #[]
  | some info =>
    info.fieldInfo.foldl (init := #[]) fun acc field =>
      let projName := name ++ field.fieldName
      match env.find? projName with
      | none => acc
      | some projInfo => acc ++ projInfo.type.getUsedConstants

/-- Get constructor-level type dependencies for inductives. -/
def getCtorTypeDeps (env : Environment) (name : Name) : Array Name :=
  match env.find? name with
  | none => #[]
  | some ci =>
    match ci with
    | .inductInfo val =>
      val.ctors.foldl (init := #[]) fun acc ctorName =>
        match env.find? ctorName with
        | none => acc
        | some ctorInfo => acc ++ ctorInfo.type.getUsedConstants
    | _ => #[]

-- ============================================================================
-- Verbatim source slicing + scope capture (additive: `source_text`,
-- `decl_namespace`, `module_opens`, `module_notations`, `module_variables`,
-- `module_context`).
--
-- The pretty-printed `type_signature`/`value` fields above are elaborated and do
-- NOT round-trip to compiling source. The fields below are raw byte slices of the
-- original `.lean` file, taken after parsing each module with Lean's own frontend
-- (so scoped notation parses). Existing fields are untouched.
-- ============================================================================

/-- First descendant (pre-order) whose kind is one of `kinds`. -/
partial def findFirstNode (stx : Syntax) (kinds : List Name) : Option Syntax :=
  if kinds.contains stx.getKind then some stx
  else match stx with
    | .node _ _ args => args.findSome? (fun a => findFirstNode a kinds)
    | _ => none

/-- Byte position of a declaration command's leading KEYWORD
    (`def`/`theorem`/`structure`/`class`/`instance`/`abbrev`/`opaque`/`axiom`/
    `lemma`/…), i.e. the start of the actual declaration syntax AFTER any leading
    doc-comment, attributes, and modifiers (`private`/`noncomputable`/…).

    A `Command.declaration` wraps a leading `declModifiers` child (doc-comment +
    attributes + modifiers) followed by the inner decl node (`Command.definition`,
    `Command.theorem`, `Command.structure`, `Command.instance`, …); that inner
    node's position is the keyword. A top-level `lemma` is its own command kind
    with the same leading `declModifiers`, so dropping the `declModifiers` child
    and taking the next child's position yields the keyword there too. Falls back
    to the command's own start position when the shape is unexpected. -/
def declKeywordPos (cmd : Syntax) : Option String.Pos.Raw :=
  match cmd with
  | .node _ k args =>
    if k == `Lean.Parser.Command.declaration then
      (args[1]?.bind (·.getPos?)) <|> cmd.getPos?
    else
      let rest := args.filter (fun a => a.getKind != `Lean.Parser.Command.declModifiers)
      (rest[0]?.bind (·.getPos?)) <|> cmd.getPos?
  | _ => cmd.getPos?

/-- Syntax kind of a `by tac` tactic-block term. (`Term.byTactic'`, used only by
    `show`/`suffices`, is intentionally NOT matched: replacing it would leave an
    invalid `show T sorry`.) -/
def byTacticKind : Name := `Lean.Parser.Term.byTactic

/-- Source byte ranges `[start, stop)` of the OUTERMOST `by` tactic-block term
    nodes (`Lean.Parser.Term.byTactic`) in `stx`, in pre-order. A `byTactic`
    nested inside another is NOT collected separately — recursion stops at each
    outermost hit, so `by foo (by bar)` yields a single range covering the whole
    outer block. Nodes with missing source positions are skipped. -/
partial def collectOutermostByTactics (stx : Syntax) : Array (Nat × Nat) :=
  go stx #[]
where
  go (s : Syntax) (acc : Array (Nat × Nat)) : Array (Nat × Nat) :=
    if s.getKind == byTacticKind then
      match s.getPos?, s.getTailPos? with
      | some a, some b => acc.push (a.byteIdx, b.byteIdx)
      | _, _ => acc
    else match s with
      | .node _ _ args => args.foldl (fun acc a => go a acc) acc
      | _ => acc

/-- Raw source slice for byte range `[b, e)`. Parser positions sit on UTF-8
    boundaries, so `String.fromUTF8!` never panics here. -/
def sliceBytes (bytes : ByteArray) (b e : Nat) : String :=
  String.fromUTF8! (bytes.extract b e)

private def isHWs (c : Char) : Bool :=
  c == ' ' || c == '\t' || c == '\n' || c == '\r'

/-- Drop trailing whitespace (spaces, tabs, CR, LF) from a slice. -/
def dropTrailingWs (s : String) : String :=
  (s.toList.reverse.dropWhile isHWs).reverse.foldl (·.push ·) ""

/-- Map a module name to its source path relative to the project root (cwd). -/
def modToSrcPath (mod : Name) : System.FilePath :=
  (System.FilePath.mk (String.intercalate "/" (mod.components.map (·.toString)))).addExtension "lean"

/-- `declVal` node kinds: the start of a declaration body (`:=` / `where`). -/
def declValKinds : List Name :=
  [`Lean.Parser.Command.declValSimple, `Lean.Parser.Command.declValEqns,
   `Lean.Parser.Command.whereStructInst]

/-- Notation / macro-style command kinds whose verbatim slice is surfaced per
    module. `mixfix` covers `infix`/`infixl`/`infixr`/`prefix`/`postfix`;
    `Mathlib.Notation3.notation3` is Mathlib's `notation3`. -/
def notationKinds : List Name :=
  [`Lean.Parser.Command.notation, `Lean.Parser.Command.mixfix,
   `Lean.Parser.Command.macro, `Lean.Parser.Command.macro_rules,
   `Lean.Parser.Command.syntax, `Mathlib.Notation3.notation3]

/-- True if `cmd` is a notation/macro/syntax/notation3 command. -/
def isNotationCmd (cmd : Syntax) : Bool :=
  let k := cmd.getKind
  notationKinds.contains k || (k.components.getLast?.map (· == `notation3)).getD false

-- ----------------------------------------------------------------------------
-- Per-notation metadata extraction (purely syntactic; no name resolution).
--
-- For each captured notation-family command we surface, besides its verbatim
-- `text`, a `kind` string, the literal token atoms it introduces (`tokens`),
-- and the raw identifier leaves of its right-hand side / macro expansion
-- (`rhs_idents`). The Python side resolves `rhs_idents` against the project decl
-- index by suffix-match; identifiers that don't match (Mathlib names, antiquot
-- pattern variables, local binders) are simply ignored, so over-collection is
-- harmless. Extraction never elaborates or resolves anything.
-- ----------------------------------------------------------------------------

/-- True if `k` is (or contains) a quotation antiquotation kind such as
    `term.pseudo.antiquot`. Subtrees under such a kind hold antiquotation
    variables (`$x`, `$xs`), not literal tokens or referenced constants, so they
    are skipped during token/ident collection. -/
def kindIsAntiquot (k : Name) : Bool :=
  (k.toString.splitOn "antiquot").length ≥ 2

/-- True if `k` is a syntax-quotation kind (`` `(…) ``) of any category —
    `Lean.Parser.Term.quot`, `Lean.Parser.Tactic.quot`, etc. — but NOT an
    antiquotation. The identifiers inside such a node are the constants a macro
    expansion references. -/
def kindIsQuot (k : Name) : Bool :=
  !kindIsAntiquot k && (k.toString.splitOn "quot").length ≥ 2

/-- True for the ASCII whitespace bytes (space, tab, LF, CR). UTF-8 lead and
    continuation bytes are all ≥ 0x80, so this never matches inside a multi-byte
    character. -/
def isWsByte (b : UInt8) : Bool := b == 32 || b == 9 || b == 10 || b == 13

/-- First byte offset in `[start, stop)` that is not ASCII whitespace (or `stop`
    if all whitespace). Used to start a verbatim slice at the first real token
    after a dropped leading doc-comment. -/
partial def skipLeadingWsBytes (bytes : ByteArray) (start stop : Nat) : Nat :=
  if start < stop && isWsByte bytes[start]! then skipLeadingWsBytes bytes (start + 1) stop
  else start

/-- Order-preserving de-duplication of a string array. -/
def dedupStrings (a : Array String) : Array String :=
  a.foldl (fun out s => if out.contains s then out else out.push s) #[]

/-- Collect every string-literal leaf (`Syntax.isStrLit?`) in a subtree. These
    are the literal token atoms a `notation`/`mixfix`/`syntax`/`macro` parser
    spec introduces (e.g. `"|0⟩"`, `" ⊗ "`, `"|"`). -/
partial def collectStrLits (acc : Array String) (s : Syntax) : Array String :=
  match s.isStrLit? with
  | some lit => acc.push lit
  | none =>
    match s with
    | .node _ _ args => args.foldl collectStrLits acc
    | _ => acc

/-- Collect every (non-anonymous) identifier leaf in a subtree, skipping
    antiquotation subtrees so that pattern variables (`$x`) are not collected.
    Identifiers are taken raw (`Name.toString`), unresolved. -/
partial def collectIdentLeaves (acc : Array String) (s : Syntax) : Array String :=
  match s with
  | .ident _ _ v _ => if v == Name.anonymous then acc else acc.push v.toString
  | .node _ k args => if kindIsAntiquot k then acc else args.foldl collectIdentLeaves acc
  | _ => acc

/-- Collect every string-literal leaf that is NOT inside a syntax quotation.
    For `macro`/`elab` these are the parser-spec tokens (e.g. `"qisimp_basic"`),
    keeping literals that belong to the quoted expansion body out of `tokens`. -/
partial def collectStrLitsOutsideQuot (acc : Array String) (s : Syntax) : Array String :=
  match s.isStrLit? with
  | some lit => acc.push lit
  | none =>
    match s with
    | .node _ k args => if kindIsQuot k then acc else args.foldl collectStrLitsOutsideQuot acc
    | _ => acc

/-- True if a subtree contains a syntax quotation (`` `(…) `` of any category). -/
partial def subtreeHasQuot (s : Syntax) : Bool :=
  match s with
  | .node _ k args => kindIsQuot k || args.any subtreeHasQuot
  | _ => false

/-- Collect identifier leaves that occur INSIDE syntax quotations, skipping
    antiquotation variables. Used for `macro`/`macro_rules`/`elab_rules`
    expansions where the referenced constants live in the quoted body and the
    surrounding `do`-block idents (`result`, `getElems`, …) are not what we want. -/
partial def collectQuotIdentLeaves (acc : Array String) (s : Syntax) : Array String :=
  match s with
  | .node _ k args =>
    if kindIsQuot k then collectIdentLeaves acc s
    else if kindIsAntiquot k then acc
    else args.foldl collectQuotIdentLeaves acc
  | _ => acc

/-- Collect literal atom values from a quotation pattern, skipping antiquotation
    subtrees and the quotation delimiters (`` `( ``, `)`). These are the literal
    tokens a `macro_rules`/`elab_rules` match pattern introduces (e.g. `⟨`, `,`,
    `|` for a `⟨ … |` bra pattern). -/
partial def collectPatternAtoms (acc : Array String) (s : Syntax) : Array String :=
  match s with
  | .atom _ v => if v.startsWith "`(" || v == ")" then acc else acc.push v
  | .node _ k args => if kindIsAntiquot k then acc else args.foldl collectPatternAtoms acc
  | _ => acc

/-- Collect pattern atoms from every syntax quotation in a subtree. -/
partial def collectQuotAtoms (acc : Array String) (s : Syntax) : Array String :=
  match s with
  | .node _ k args =>
    if kindIsQuot k then collectPatternAtoms acc s
    else args.foldl collectQuotAtoms acc
  | _ => acc

/-- Collect every `matchAlt` node in a subtree (the `| pat => rhs` arms of a
    `macro_rules`/`elab_rules` command). -/
partial def collectMatchAlts (acc : Array Syntax) (s : Syntax) : Array Syntax :=
  match s with
  | .node _ k args =>
    let acc := if k == `Lean.Parser.Term.matchAlt then acc.push s else acc
    args.foldl collectMatchAlts acc
  | _ => acc

/-- Split a command's direct args at the first top-level `=>` atom into the
    parser-spec part (before) and the RHS-term part (after). `none` when there is
    no top-level `=>` (e.g. a `syntax` command, or `macro_rules` whose `=>` sit
    inside nested match arms). -/
def argsSplitOnArrow (args : Array Syntax) : Option (Array Syntax × Array Syntax) :=
  match args.findIdx? (fun a => match a with | .atom _ v => v == "=>" | _ => false) with
  | some i => some (args.extract 0 i, args.extract (i + 1) args.size)
  | none => none

/-- The specific mixfix keyword (`infixl`/`infixr`/`infix`/`prefix`/`postfix`)
    of a `Lean.Parser.Command.mixfix` node, read from its keyword child node;
    `"mixfix"` if none is found. -/
def mixfixKeyword (inner : Syntax) : String :=
  let kws := ["infixl", "infixr", "infix", "prefix", "postfix"]
  match inner.getArgs.findSome? (fun a =>
    match a.getKind.components.getLast?.map (·.toString) with
    | some s => if kws.contains s then some s else none
    | none => none) with
  | some s => s
  | none => "mixfix"

/-- The `kind` string for a captured notation-family command: the specific
    mixfix keyword for `mixfix`, otherwise the last component of the command kind
    (`notation`, `macro_rules`, `syntax`, `macro`, `notation3`, …). -/
def notationKindString (inner : Syntax) : String :=
  let k := inner.getKind
  if k == `Lean.Parser.Command.mixfix then mixfixKeyword inner
  else (k.components.getLast?.map (·.toString)).getD "notation"

/-- Peel off `… in <cmd>` wrappers (kind `Lean.Parser.Command.in`, e.g.
    `set_option … in`, possibly nested) to reach the innermost wrapped command. -/
partial def unwrapInCommands (cmd : Syntax) : Syntax :=
  if cmd.getKind == `Lean.Parser.Command.in then
    match cmd.getArgs.back? with
    | some inner => unwrapInCommands inner
    | none => cmd
  else cmd

/-- The inner notation-family command of a top-level command, looking through any
    `… in` wrappers, or `none` if the (unwrapped) command is not a notation-family
    command. The verbatim `text` is sliced from the OUTER command (so a
    `set_option … in` prefix is retained); tokens/idents come from this inner. -/
def notationInnerCmd? (cmd : Syntax) : Option Syntax :=
  let inner := unwrapInCommands cmd
  if isNotationCmd inner then some inner else none

/-- Identifier leaves of a notation RHS. When the RHS contains a term quotation
    (macro expansion), restrict to identifiers inside quotations; otherwise take
    all identifier leaves of the plain RHS term. -/
def rhsIdentsOfArgs (after : Array Syntax) : Array String :=
  if after.any subtreeHasQuot then after.foldl collectQuotIdentLeaves #[]
  else after.foldl collectIdentLeaves #[]

/-- `(tokens, rhs_idents)` for a `macro_rules`/`elab_rules` command: pattern atoms
    of each match arm's LHS quotation, and identifier leaves of each arm's RHS
    expansion quotations. -/
def notationMetaFromMatchAlts (inner : Syntax) : Array String × Array String :=
  (collectMatchAlts #[] inner).foldl (init := (#[], #[]))
    fun (acc : Array String × Array String) alt =>
      match argsSplitOnArrow alt.getArgs with
      | some (before, after) =>
        (before.foldl collectQuotAtoms acc.1, after.foldl collectQuotIdentLeaves acc.2)
      | none => acc

/-- `(tokens, rhs_idents)` for any captured notation-family inner command,
    dispatched on its kind:

    * `syntax` — tokens are all string-literal atoms of the parser spec; no RHS.
    * `macro_rules` / `elab_rules` — per match arm (`notationMetaFromMatchAlts`).
    * `macro` (and any notation whose body is a syntax quotation, e.g. a tactic
      macro): tokens are the string literals OUTSIDE the quotation, `rhs_idents`
      the identifier leaves inside the expansion quotation.
    * everything else (`notation` / `mixfix` / `notation3` / …) — split on the
      top-level `=>`: tokens are the string-literal atoms before it, `rhs_idents`
      the identifier leaves after it.

    Both lists are order-preserving de-duplicated. -/
def notationTokensIdents (inner : Syntax) : Array String × Array String :=
  let k := inner.getKind
  let raw :=
    if k == `Lean.Parser.Command.syntax then
      (collectStrLits #[] inner, (#[] : Array String))
    else if k == `Lean.Parser.Command.macro_rules || k == `Lean.Parser.Command.elab_rules then
      notationMetaFromMatchAlts inner
    else if subtreeHasQuot inner then
      (collectStrLitsOutsideQuot #[] inner, collectQuotIdentLeaves #[] inner)
    else
      match argsSplitOnArrow inner.getArgs with
      | some (before, after) => (before.foldl collectStrLits #[], rhsIdentsOfArgs after)
      | none => (collectStrLits #[] inner, (#[] : Array String))
  (dedupStrings raw.1, dedupStrings raw.2)

/-- True if `cmd` declares one or more constants. Top-level `lemma` is its own
    kind (not wrapped in `Command.declaration`); everything else
    (def/theorem/abbrev/structure/inductive/instance/opaque/axiom/example) is a
    `Command.declaration`. -/
def isDeclCmd (cmd : Syntax) : Bool :=
  let k := cmd.getKind
  k == `Lean.Parser.Command.declaration || k.toString.endsWith "lemma"

/-- Command kinds whose elaboration updates parser-relevant scope: namespace /
    section nesting and the set of `open`ed (and `open scoped`) namespaces govern
    which scoped notations are active when parsing subsequent declarations;
    `set_option` can change parser behaviour; `universe`/`variable` round out the
    scope state. These never import library modules, so elaborating them against
    the global environment is cheap. -/
def contextCmdKinds : List Name :=
  [`Lean.Parser.Command.namespace, `Lean.Parser.Command.section,
   `Lean.Parser.Command.end, `Lean.Parser.Command.open,
   `Lean.Parser.Command.variable, `Lean.Parser.Command.universe,
   `Lean.Parser.Command.set_option]

/-- True if `cmd` is a context command that must be elaborated (against the global
    environment) to keep the scoped-notation parser state correct for parsing the
    declarations that follow it: a scope command (`contextCmdKinds`), a
    notation/macro/syntax command (`isNotationCmd`), or an `elab`/`elab_rules`/
    `declare_syntax_cat` command that registers new term syntax. -/
def isContextCmd (cmd : Syntax) : Bool :=
  let k := cmd.getKind
  contextCmdKinds.contains k
    || isNotationCmd cmd
    || (k.components.getLast?.map
          (fun c => c == `elab || c == `elab_rules || c == `declare_syntax_cat)
        ).getD false

/-- True if `cmd` is a top-level command whose verbatim slice belongs in a
    module's `module_context` — the elaboration context a downstream verbatim copy
    must reproduce to elaborate. This is every top-level command EXCEPT:

    * declarations (`isDeclCmd`: def/theorem/abbrev/structure/inductive/instance/
      opaque/axiom/example/lemma), `mutual` blocks, and `… in <cmd>` wrappers
      (kind `Lean.Parser.Command.in`, e.g. `set_option … in <decl>`,
      `attribute … in <decl>`) — each carries a declaration body the copy already
      emits separately, so re-emitting it would duplicate the declaration;
    * structural scope delimiters (`namespace`/`section`/`end`) — the copy is
      wrapped in its own namespace that opens the real ones;
    * notation/macro/syntax + elab-family commands (`isNotationCmd` plus
      `elab`/`elab_rules`/`declare_syntax_cat`) — the real imported modules already
      provide them, so re-emitting would redundantly re-declare notation;
    * module doc comments (`/-! … -/`, kind `moduleDoc`) — documentation, not
      elaboration context.

    What remains — `open`, `open scoped`, `variable`, `set_option`, `attribute`,
    `universe`, and any other contextual command — is captured verbatim, in source
    order, so a downstream copy can reproduce the module's local instances, option
    settings, opened namespaces, and section variables. The capture site
    additionally drops `#`-prefixed diagnostic commands (`#check`/`#eval`/… ), which
    are non-contextual and could error or run IO if re-emitted. -/
def isModuleContextCmd (cmd : Syntax) : Bool :=
  let k := cmd.getKind
  if isDeclCmd cmd then false
  else if k == `Lean.Parser.Command.mutual || k == `Lean.Parser.Command.in then false
  else if k == `Lean.Parser.Command.namespace || k == `Lean.Parser.Command.section
       || k == `Lean.Parser.Command.end then false
  else if k == `Lean.Parser.Command.moduleDoc then false
  else if isNotationCmd cmd then false
  else if (k.components.getLast?.map
            (fun c => c == `elab || c == `elab_rules || c == `declare_syntax_cat)).getD false then false
  else true

/-- Name opened by a `namespace Foo.Bar` command (`anonymous` if not found). -/
def namespaceCmdName (cmd : Syntax) : Name :=
  (cmd.getArgs[1]?.map (·.getId)).getD .anonymous

/-- The current namespace string from a scope stack. `some n` frames are
    `namespace` openings (contribute their name); `none` frames are `section`
    openings (contribute nothing). The stack is innermost-first. -/
def stackNamespace (stack : List (Option Name)) : String :=
  String.intercalate "." ((stack.reverse.filterMap id).map (·.toString))

/-- Source-slice boundaries + active namespace for one declaration command. -/
structure SliceInfo where
  /-- Byte offset of the declaration start, taken from the env's `declRangeExt`
      range (the start of the docstring / attributes / modifiers). -/
  startByte    : Nat
  /-- Byte offset one past the declaration end, taken from the env's `declRangeExt`
      range. Authoritative even when the parse-only command Syntax was truncated. -/
  tailByte     : Nat
  /-- Byte offset of the declaration body (`:=` / `where`), from the parse-only
      command. Kept only when it lies inside `[startByte, tailByte]`; `none` forces
      a whole-declaration verbatim slice (the correct fallback for truncated parses). -/
  declValByte? : Option Nat
  /-- Byte ranges of the OUTERMOST `by` tactic-block terms inside this declaration,
      each filtered to lie within `[startByte, tailByte]`, as ABSOLUTE source byte
      offsets. `source_text` is emitted as the RAW verbatim slice (no pre-splicing);
      these ranges are re-emitted (rebased onto the slice start) as `byTactic_ranges`
      so the consumer can splice its own elision token (`sorry` for live re-declared
      copies, `⋯` for commented digests) over the proof bodies. -/
  byTacticRanges : Array (Nat × Nat)
  /-- 1-indexed source line of the declaration KEYWORD (`def`/`theorem`/`structure`/…),
      taken from the parse-only command after skipping any leading doc-comment,
      attributes, and modifiers. `none` when the keyword position is unavailable
      (falls back to the `declRangeExt` selection range at emit time). -/
  keywordLine : Option Nat
  /-- Namespace open at this command's position (`""` if none). -/
  declNamespace : String

/-- Parsed, slice-ready view of one module's source. -/
structure ModuleSlice where
  /-- Raw UTF-8 source bytes. -/
  bytes : ByteArray
  /-- Primary declaration name → slice boundaries + namespace. The primary name of
      a command is the earliest-starting declared constant in it, tie-broken to the
      shortest name (the structure/inductive/def itself, not its projections/ctors). -/
  nameToCmd : Std.HashMap Name SliceInfo
  /-- Verbatim slices of `open` / `open scoped` commands, in source order. -/
  opens : Array String
  /-- Per-notation metadata objects (`text`/`line`/`kind`/`tokens`/`rhs_idents`)
      for notation/macro/syntax commands, including those wrapped in
      `set_option … in`, in source order. -/
  notations : Array Json
  /-- Verbatim slices of file-level `variable` commands, in source order. -/
  variables : Array String
  /-- Verbatim slices of every context command (`isModuleContextCmd`: opens,
      `open scoped`, `variable`, `set_option`, `attribute`, `universe`, …), in
      source order. Superset of `opens`/`variables`; excludes declarations,
      `namespace`/`section`/`end`, and notation-family commands. -/
  contextCmds : Array String

/-- Parse a module's source against the GLOBAL imported environment and build a
    `ModuleSlice`: declaration → slice boundaries (with active namespace) plus the
    verbatim open/notation/variable/context-command slices. Returns `none` if the
    source file is missing.

    Slice boundaries come from the env's `declRangeExt` range (authoritative end,
    robust to truncated parse-only command Syntax), NOT from the parse-only
    command's tail position; the parse-only command supplies only the declaration
    body boundary (`:=` / `where`) and the active namespace/scope state.

    Memory invariant: this NEVER re-imports the module's transitive dependencies
    and NEVER re-elaborates its declarations. The single `globalEnv` (already
    holding every project + library module and every parser/notation extension) is
    reused for every module in the export, so peak memory is independent of the
    module count.

    Mechanism: parse the header only to skip past the `import` lines (the global
    env already supplies every import), then drive a manual command loop seeded
    with a `Command.State` over `globalEnv`. For each parsed command:

    * CONTEXT commands (`isContextCmd`: namespace/section/end/open/variable/
      universe/set_option and the notation/macro/syntax/elab families) are
      elaborated so scoped notation / open / section state is correct for parsing
      the declarations that follow. These are cheap and pull in no library module.
      Elaboration errors are logged to stderr and skipped (best-effort).
    * DECLARATION commands are parsed only — their `Syntax` drives source slicing.
      They are NOT elaborated: the global env already contains the elaborated
      decls, and re-declaring them would both clash and reintroduce the per-module
      memory cost this design eliminates.

    Byte positions come from `declRangeExt.find? globalEnv` over the module's own
    `constNames`; those positions are in the module's source, matching the
    `fileMap` of the source we read. Private declarations already carry their
    imported mangled names in `constNames`, so no `setMainModule` is needed. -/
unsafe def parseModuleForSlicing (globalEnv : Environment) (mod : Name)
    (constNames : Array Name) : IO (Option ModuleSlice) := do
  let srcPath := modToSrcPath mod
  unless (← srcPath.pathExists) do return none
  let input ← IO.FS.readFile srcPath
  let bytes := input.toByteArray
  let inputCtx := Lean.Parser.mkInputContext input srcPath.toString
  let fm := inputCtx.fileMap
  -- Parse (and discard) the header: we need only the parser position past the
  -- `import` lines. The global env already supplies every imported module.
  let (_, headerState, headerMessages) ← Lean.Parser.parseHeader inputCtx
  -- Byte span of every constant declared in this module, read from the GLOBAL
  -- env's declaration ranges (no per-module elaboration). `spanByName` holds the
  -- authoritative [start, end) used for slicing; `posNames` (start byte → name)
  -- drives command → primary-declaration association in the parse loop.
  let mut posNames : Array (Nat × Name) := #[]
  let mut spanByName : Std.HashMap Name (Nat × Nat) := {}
  for name in constNames do
    match declRangeExt.find? globalEnv name with
    | some r =>
      let sB := (fm.ofPosition r.range.pos).byteIdx
      let eB := (fm.ofPosition r.range.endPos).byteIdx
      posNames := posNames.push (sB, name)
      spanByName := spanByName.insert name (sB, eB)
    | none => pure ()
  let mut nameToCmd : Std.HashMap Name SliceInfo := {}
  let mut opens : Array String := #[]
  let mut notations : Array Json := #[]
  let mut variables : Array String := #[]
  let mut contextCmds : Array String := #[]
  let mut nsStack : List (Option Name) := []
  -- Manual command loop seeded with the global env. Holds exactly ONE environment
  -- for the whole run (context-command elaboration only ever mutates a small delta
  -- on top of the shared `globalEnv`, discarded when this module is done).
  let mut cmdState := Lean.Elab.Command.mkState globalEnv headerMessages {}
  let mut pstate := headerState
  repeat
    let scope := cmdState.scopes.head!
    let pmctx : Lean.Parser.ParserModuleContext :=
      { env := cmdState.env, options := scope.opts,
        currNamespace := scope.currNamespace, openDecls := scope.openDecls }
    let cmdPos := pstate.pos
    let (cmd, pstate', msgs') :=
      Lean.Parser.parseCommand inputCtx pmctx pstate cmdState.messages
    pstate := pstate'
    cmdState := { cmdState with messages := msgs' }
    if Lean.Parser.isTerminalCommand cmd then break
    -- Keep parser scope correct for subsequent declarations by elaborating only
    -- context commands. Declarations are never re-elaborated.
    if isContextCmd cmd then
      let cmdCtx : Lean.Elab.Command.Context :=
        { cmdPos := cmdPos, fileName := inputCtx.fileName, fileMap := fm,
          snap? := none, cancelTk? := none }
      match ← (((Lean.Elab.Command.elabCommand cmd) cmdCtx).run cmdState).toIO' with
      | .ok (_, st) => cmdState := st
      | .error ex =>
        IO.eprintln s!"[ExportSigs] {mod}: skipped context command at byte \
          {cmdPos.byteIdx}: {← ex.toMessageData.toString}"
    -- Capture the verbatim slice of every context command (opens, `open scoped`,
    -- `variable`, `set_option`, `attribute`, `universe`, …) in source order. These
    -- parse cleanly, so their `getPos?`/`getTailPos?` range is exact. This runs
    -- independently of the classification below (a command can be both a context
    -- command and an `open`/`variable` captured into the dedicated arrays).
    if isModuleContextCmd cmd then
      match cmd.getPos?, cmd.getTailPos? with
      | some a, some b =>
        let sl := dropTrailingWs (sliceBytes bytes a.byteIdx b.byteIdx)
        -- Drop `#`-prefixed diagnostic commands (`#check`/`#eval`/…): non-contextual.
        -- `getPos?` sits on the first token (after leading trivia), so the slice has
        -- no leading whitespace and a `#` command starts the slice directly.
        unless sl.startsWith "#" do
          contextCmds := contextCmds.push sl
      | _, _ => pure ()
    -- Source slicing + scope-slice capture (identical classification to before).
    let k := cmd.getKind
    if k == `Lean.Parser.Command.namespace then
      nsStack := some (namespaceCmdName cmd) :: nsStack
    else if k == `Lean.Parser.Command.section then
      nsStack := none :: nsStack
    else if k == `Lean.Parser.Command.end then
      nsStack := match nsStack with | _ :: rest => rest | [] => []
    else if k == `Lean.Parser.Command.open then
      match cmd.getPos?, cmd.getTailPos? with
      | some a, some b => opens := opens.push (dropTrailingWs (sliceBytes bytes a.byteIdx b.byteIdx))
      | _, _ => pure ()
    else if let some inner := notationInnerCmd? cmd then
      -- Notation-family command, possibly wrapped in `set_option … in` (kind
      -- `Lean.Parser.Command.in`). The verbatim `text` is sliced from the OUTER
      -- `cmd` so any `set_option … in` prefix is retained (required to re-declare
      -- precheck-disabled notations); `kind`/`tokens`/`rhs_idents` come from the
      -- INNER notation command.
      match cmd.getPos?, cmd.getTailPos? with
      | some a, some b =>
        -- Exclude a leading doc-comment from the slice: if `cmd`'s first
        -- doc-comment starts exactly at the command start, begin after it (and
        -- past the whitespace up to the first real token).
        let startPos := match findFirstNode cmd [`Lean.Parser.Command.docComment] with
          | some dc =>
            match dc.getPos?, dc.getTailPos? with
            | some dcS, some dcE => if dcS.byteIdx == a.byteIdx then dcE else a
            | _, _ => a
          | none => a
        let startB := skipLeadingWsBytes bytes startPos.byteIdx b.byteIdx
        let text := dropTrailingWs (sliceBytes bytes startB b.byteIdx)
        let (toks, ids) := notationTokensIdents inner
        notations := notations.push <| Json.mkObj [
          ("text", .str text),
          ("line", .num (fm.toPosition startPos).line),
          ("kind", .str (notationKindString inner)),
          ("tokens", .arr (toks.map .str)),
          ("rhs_idents", .arr (ids.map .str))
        ]
      | _, _ => pure ()
    else if k == `Lean.Parser.Command.variable then
      match cmd.getPos?, cmd.getTailPos? with
      | some a, some b => variables := variables.push (dropTrailingWs (sliceBytes bytes a.byteIdx b.byteIdx))
      | _, _ => pure ()
    else if isDeclCmd cmd then
      match cmd.getPos?, cmd.getTailPos? with
      | some cs, some ct =>
        let cmdStartB := cs.byteIdx
        let cmdTailB := ct.byteIdx
        let dvB? := (findFirstNode cmd declValKinds).bind (·.getPos?) |>.map (·.byteIdx)
        let cands := posNames.filter (fun (b, _) => cmdStartB ≤ b && b < cmdTailB)
        if h : cands.size > 0 then
          let minB := cands.foldl (fun m (b, _) => min m b) cands[0].1
          let atMin := cands.filterMap (fun (b, n) => if b == minB then some n else none)
          if h2 : atMin.size > 0 then
            let primary := atMin.foldl (fun best n =>
              if n.toString.length < best.toString.length then n else best) atMin[0]
            -- Take the slice SPAN from the authoritative env range, not from the
            -- (possibly truncated) parse-only command. The parse-only command
            -- supplies only the declaration-body boundary, kept only when it lies
            -- inside the authoritative span (else fall back to a whole-decl slice).
            match spanByName.get? primary with
            | some (sB, eB) =>
              let dvInRange? := match dvB? with
                | some d => if sB ≤ d && d ≤ eB then some d else none
                | none => none
              -- Outermost `by` blocks inside this command, clamped to the
              -- authoritative declaration span (guards truncated parses).
              let byRanges := (collectOutermostByTactics cmd).filter
                (fun (a, b) => sB ≤ a && b ≤ eB)
              -- 1-indexed source line of the declaration keyword (after any
              -- leading doc-comment / attributes / modifiers).
              let kwLine? := (declKeywordPos cmd).map (fun p => (fm.toPosition p).line)
              nameToCmd := nameToCmd.insert primary
                { startByte := sB, tailByte := eB, declValByte? := dvInRange?,
                  byTacticRanges := byRanges, keywordLine := kwLine?,
                  declNamespace := stackNamespace nsStack }
            | none => pure ()
      | _, _ => pure ()
    else pure ()
  return some { bytes, nameToCmd, opens, notations, variables, contextCmds }

/-- The body replacement to append to a truncated declaration slice, or `none`
    to keep the declaration whole (verbatim).

    The downstream consumer re-emits each `source_text` as a copy in a fresh
    namespace that `import`s the real modules and audits whether DEFINITIONS are
    STATED correctly. Proof status is irrelevant to that audit, so:

    * Prop-typed decls (theorem/lemma/Prop-valued `def`/`instance`) → ` := by sorry`
      (their body is a proof, which the audit ignores).
    * everything else — `def`/`instance`/`opaque` with a non-`Prop` type, `abbrev`,
      and `structure`/`inductive`/`class` — is kept WHOLE (`none`): the data body,
      fields, and constructors ARE the audited content.
    * `axiom` carries no body, so either branch yields its signature only.

    A data body may name a module-`private` helper in a proof field (e.g. a
    structure-constructing `def` whose `isHermitian` field calls a private lemma).
    A digest copy cannot resolve that private name, but the resulting elaboration
    error is localized to that field and does not cascade — and the data body, which
    is what the audit reads, is shown verbatim regardless. -/
def truncationSuffix (isProp : Bool) : Option String :=
  if isProp then some " := by sorry" else none

/-- Rebase the absolute `by`-block byte ranges `si.byTacticRanges` onto the slice
    that starts at `si.startByte`: subtract the slice start from each endpoint and
    clamp to `[0, sliceLen]`. The result is a sorted, non-overlapping array of
    `(start, stop)` BYTE offsets RELATIVE to the start of `source_text`, suitable
    for the consumer to byte-splice its own elision token (`sorry` / `⋯`) over.

    `sliceLen` is the UTF-8 byte length of the emitted `source_text` (i.e.
    `tailByte - startByte` for a raw slice). Ranges entirely outside `[0, sliceLen]`
    after rebasing collapse to empty `(start = stop)` and are dropped. -/
def rebaseByTacticRanges (si : SliceInfo) (sliceLen : Nat) : Array (Nat × Nat) :=
  let s0 := si.startByte
  (si.byTacticRanges.filterMap fun (a, b) =>
    let a' := (if a ≥ s0 then a - s0 else 0)
    let b' := (if b ≥ s0 then b - s0 else 0)
    let a'' := min a' sliceLen
    let b'' := min b' sliceLen
    if a'' < b'' then some (a'', b'') else none).qsort (fun x y => x.1 < y.1)

/-- The verbatim `source_text` slice for a declaration plus the slice-relative
    `by`-block byte ranges to elide.

    * Non-truncated decls (`bodySuffix? = none`: data `def`/`instance`/`opaque`,
      `abbrev`, `structure`/`inductive`/`class`) → the RAW verbatim slice
      `bytes[startByte, tailByte)`, returned byte-for-byte with NO token spliced in.
      The accompanying ranges (`rebaseByTacticRanges`) mark each OUTERMOST `by`
      block so the consumer can splice its own elision token (`sorry` for a live
      re-declared copy that must typecheck, `⋯` for a commented digest) — e.g.
      splicing `⋯` over the three ranges of `DensityOp.fromPure` yields
      `⟨⟨⟨ψ * ψ.dag, ⋯⟩, ⋯⟩, ⋯⟩`.
    * Truncated decls (`bodySuffix? = some s`: Prop-typed theorem/lemma/`def`/
      `instance`) → the statement up to the body boundary (`:=` / `where`) re-closed
      with `s` (` := by sorry`). These are surfaced via `#check` anyway and carry no
      source `by` block in their emitted slice, so the ranges are empty. When no body
      boundary was found, the raw slice is emitted with its `by`-block ranges instead. -/
def sliceSourceText (bytes : ByteArray) (si : SliceInfo) (bodySuffix? : Option String) :
    String × Array (Nat × Nat) :=
  match bodySuffix? with
  | some suffix =>
    match si.declValByte? with
    | some dvB => (dropTrailingWs (sliceBytes bytes si.startByte dvB) ++ suffix, #[])
    | none =>
      let text := sliceBytes bytes si.startByte si.tailByte
      (text, rebaseByTacticRanges si (si.tailByte - si.startByte))
  | none =>
    let text := sliceBytes bytes si.startByte si.tailByte
    (text, rebaseByTacticRanges si (si.tailByte - si.startByte))

/-- Decide whether a declaration's TYPE is a `Prop` (so its body is a proof to be
    replaced by ` := by sorry`). Covers theorem/lemma and Prop-valued defs/instances. -/
def isPropTypeIO (env : Environment) (type : Expr) : IO Bool := do
  match ← runMetaIO env (do return (← Meta.isProp type)) with
  | .ok b => return b
  | .error _ => return false

/-- Module filter parsed from CLI args after the root module.
    No args after root → emit every project-local module (`none`).
    Args present → emit only declarations from those modules. -/
def parseModuleFilter (args : List String) : Option NameHashSet :=
  if args.isEmpty then none
  else some (args.foldl (init := ({} : NameHashSet)) fun s m => s.insert m.toName)

unsafe def main : List String → IO Unit := fun args => do
  let rootModuleStr ← match args.head? with
    | some m => pure m
    | none =>
      IO.eprintln "Usage: lake env lean --run ExportSigs.lean <RootModule> [<Mod1> <Mod2> ...]"
      IO.eprintln "With filter: lake env lean --run ExportSigs.lean QuantumInformation QuantumInformation.Foo QuantumInformation.Bar"
      IO.Process.exit 1

  let rootModule := rootModuleStr.toName
  let moduleFilter := parseModuleFilter args.tail

  enableInitializersExecution
  initSearchPath (← findSysroot)
  -- loadExts := true is required so that PersistentEnvExtension states (including
  -- @[app_unexpander] registrations) are populated by calling each extension's
  -- addImportedFn. Without this, ppExpr cannot find unexpanders for notations like
  -- `^`, `*`, `≤`, `→ₗ[R]` and falls back to showing HPow.hPow, HMul.hMul, etc.
  let env ← importModules #[{ module := rootModule }] {} (loadExts := true)

  let mods := env.header.moduleNames
  let rootName := rootModule.getRoot

  -- Collect all project declaration names and namespaces
  let mut projectNames : NameHashSet := {}
  let mut projectNamespaces : NameHashSet := {}
  for i in [:mods.size] do
    if mods[i]!.getRoot != rootName then continue
    -- Add module name itself as a namespace to open
    projectNamespaces := projectNamespaces.insert mods[i]!
    let md := env.header.moduleData[i]!
    for j in [:md.constNames.size] do
      projectNames := projectNames.insert md.constNames[j]!
      -- Also add all parent namespaces of each declaration
      let mut ns := md.constNames[j]!
      while true do
        match ns with
        | .str parent _ =>
          if parent != .anonymous then
            projectNamespaces := projectNamespaces.insert parent
          ns := parent
        | _ => break

  -- Global open decls: open all project namespaces for shorter cross-module names
  let mut globalOpenDecls : List OpenDecl := []
  for ns in projectNamespaces.toList do
    globalOpenDecls := .simple ns [] :: globalOpenDecls

  -- Build class name lookup (classExtension.getState doesn't merge imports)
  let mut classNames : NameHashSet := {}
  for i in [:mods.size] do
    for e in classExtension.getModuleEntries env i do
      classNames := classNames.insert e.name

  -- Build instance name lookup (instanceExtension.getState doesn't merge imports)
  let mut instanceNames : NameHashSet := {}
  for i in [:mods.size] do
    for e in instanceExtension.ext.getModuleEntries env i do
      match e with
      | .global entry | .scoped _ entry =>
        if let some gn := entry.globalName? then
          instanceNames := instanceNames.insert gn

  -- Helper: collect deps for a declaration (type + prop-erased value + fields + ctors)
  let collectDeps := fun (name : Name) (cinfo : ConstantInfo) => do
    -- Type signature deps
    let mut allConsts := getTypeConstants cinfo
    -- Value deps (with Prop subexprs erased, so proof deps are excluded)
    match cinfo with
    | .defnInfo v =>
      let valueDeps ← getNonPropConstants env projectNames v.value
      allConsts := allConsts ++ valueDeps
    | _ => pure ()
    -- For structures: add field type deps
    allConsts := allConsts ++ getFieldTypeDeps env name
    -- For inductives: add constructor type deps
    allConsts := allConsts ++ getCtorTypeDeps env name

    let mut seen : NameHashSet := {}
    let mut projectDeps : Array String := #[]
    for c in allConsts do
      if c == name then continue
      if !projectNames.contains c then continue
      if seen.contains c then continue
      if c.isInternalDetail && (findParent c projectNames).isSome then continue
      -- Keep all project deps (not just sorry ones — we want full type context)
      seen := seen.insert c
      projectDeps := projectDeps.push c.toString
    pure projectDeps

  -- Build JSON
  let mut decls : Array Json := #[]
  let mut emittedNames : NameHashSet := {}
  -- Per-module verbatim scope slices, keyed by module name (modules in the export).
  let mut moduleOpens : Array (String × Json) := #[]
  let mut moduleNotations : Array (String × Json) := #[]
  let mut moduleVariables : Array (String × Json) := #[]
  let mut moduleContext : Array (String × Json) := #[]

  for i in [:mods.size] do
    if mods[i]!.getRoot != rootName then continue
    -- Apply module filter (if any) to the EMISSION loop only.
    -- The setup loops above (projectNames, namespaces, classes, instances) stay
    -- unfiltered so that dep tracking and namespace shortening remain correct.
    if let some filter := moduleFilter then
      if !filter.contains mods[i]! then continue
    let md := env.header.moduleData[i]!
    let modStr := mods[i]!.toString

    -- Parse this module's source for verbatim `source_text`/`decl_namespace` and
    -- collect its open/notation/variable slices. Parsing runs against the single
    -- global env (no per-module re-import / re-elaboration), so peak memory is
    -- independent of how many modules the export covers.
    let mslice? ← parseModuleForSlicing env mods[i]! md.constNames
    match mslice? with
    | some ms =>
      moduleOpens := moduleOpens.push (modStr, .arr (ms.opens.map .str))
      moduleNotations := moduleNotations.push (modStr, .arr ms.notations)
      moduleVariables := moduleVariables.push (modStr, .arr (ms.variables.map .str))
      moduleContext := moduleContext.push (modStr, .arr (ms.contextCmds.map .str))
    | none => pure ()

    for j in [:md.constNames.size] do
      let name := md.constNames[j]!
      if emittedNames.contains name then continue
      emittedNames := emittedNames.insert name

      -- Skip auto-generated sub-declarations from rendered signature context.
      if name.isInternalDetail then
        if (declRangeExt.find? env name).isNone then
          if (findParent name projectNames).isSome then continue

      -- Skip auto-generated boilerplate (noConfusion, recOn, casesOn, etc.)
      if isAutoGenerated name projectNames then continue

      let some cinfo := env.find? name | continue
      let some kind := getKind cinfo | continue

      let isPrivate := name.isInternal

      -- Pretty-print the type signature with project namespaces open
      let typeStr ← ppExprStrIn env name cinfo.type globalOpenDecls

      -- Collect project deps (type + prop-erased value + fields + ctors)
      let deps ← collectDeps name cinfo

      -- Line number: 1-indexed source line of the declaration KEYWORD. Prefer the
      -- parse-only keyword position from this module's slice (skips any leading
      -- doc-comment / attributes / modifiers); fall back to the env's
      -- `selectionRange` (the declaration name, on the keyword's line) for
      -- sub-declarations with no slice. Both are 1-indexed (no `+1`).
      let sliceForName? := mslice?.bind (·.nameToCmd.get? name)
      let lineNum : Option Nat :=
        match sliceForName?.bind (·.keywordLine) with
        | some l => some l
        | none =>
          match declRangeExt.find? env name with
          | some range => some range.selectionRange.pos.line
          | none => none

      -- Structure fields
      let fieldsJson ← getStructureFields env name globalOpenDecls

      -- Inductive constructors
      let ctorsJson ← getConstructors env name globalOpenDecls

      -- Check if this is an abbrev (unfoldable def)
      let isAbbrev := match cinfo with
        | .defnInfo v => v.hints.isAbbrev
        | _ => false

      -- Sorry check: transitive through _proof_N sub-declarations
      let hasSorry := hasSorryTransitiveCheck env cinfo

      -- Pretty-print the value (prop-erased for defs, raw for abbrevs)
      -- For sorry-containing defs, keep proofs visible so sorry locations are shown
      let valueStr ← match cinfo with
        | .defnInfo v =>
          if isAbbrev then
            let s ← ppExprStrIn env name v.value globalOpenDecls
            pure (some s)
          else
            let s ← ppValueStr env projectNames name v.value globalOpenDecls
            pure (some s)
        | _ => pure none

      -- Refine kind: distinguish structure/class/instance from plain inductive/def
      let refinedKind :=
        if isAbbrev then "abbrev"
        else if kind == "inductive" then
          if classNames.contains name then "class"
          else if (getStructureInfo? env name).isSome then "structure"
          else kind
        else if kind == "def" && instanceNames.contains name then "instance"
        else kind

      let mut jsonFields : Array (String × Json) := #[
        ("name", .str name.toString),
        ("kind", .str refinedKind),
        ("module", .str modStr),
        ("is_private", .bool isPrivate),
        ("type_signature", .str typeStr),
        ("deps", .arr (deps.map .str))
      ]

      if hasSorry then
        jsonFields := jsonFields.push ("has_sorry", .bool true)

      match lineNum with
      | some l => jsonFields := jsonFields.push ("line", .num l)
      | none => pure ()

      match fieldsJson with
      | some fs => jsonFields := jsonFields.push ("fields", .arr fs)
      | none => pure ()

      match ctorsJson with
      | some cs => jsonFields := jsonFields.push ("constructors", .arr cs)
      | none => pure ()

      -- Structure parent names (from `extends`)
      match getStructureParentNames env name with
      | some ps => jsonFields := jsonFields.push ("parents", .arr ps)
      | none => pure ()

      match valueStr with
      | some v => jsonFields := jsonFields.push ("value", .str v)
      | none => pure ()

      -- Docstring
      match ← findDocString? env name with
      | some doc => jsonFields := jsonFields.push ("docstring", .str doc)
      | none => pure ()

      -- Verbatim source slice + active namespace (additive). Attached to the
      -- primary declaration of each command; omitted for sub-declarations
      -- (projections, constructors) that share a command with their parent.
      match mslice?, sliceForName? with
      | some ms, some si =>
        let isProp ← isPropTypeIO env cinfo.type
        -- Data bodies (`def`/`instance`/`opaque`/`abbrev`/`structure`/…) are kept
        -- verbatim; only Prop-typed proof bodies are truncated (see `truncationSuffix`).
        let bodySuffix? := truncationSuffix isProp
        -- `source_text` is the RAW verbatim slice (no token pre-spliced); the
        -- `byTactic_ranges` are slice-relative byte offsets the consumer splices
        -- its own elision token (`sorry` / `⋯`) over.
        let (text, byRanges) := sliceSourceText ms.bytes si bodySuffix?
        let byRangesJson := byRanges.map (fun (a, b) => Json.arr #[.num a, .num b])
        jsonFields := jsonFields.push ("source_text", .str text)
        jsonFields := jsonFields.push ("byTactic_ranges", .arr byRangesJson)
        jsonFields := jsonFields.push ("decl_namespace", .str si.declNamespace)
      | _, _ => pure ()

      decls := decls.push <| Json.mkObj jsonFields.toList

  -- Canonical project module set: every module reachable from the root via
  -- `importModules`. Lake doesn't always delete oleans for removed imports,
  -- so this is the authoritative truth Python uses to garbage-collect stale
  -- cache entries that survive a disk walk.
  let mut projectModules : Array Json := #[]
  -- Direct imports of EVERY project-local module (root == rootName), emitted
  -- UNFILTERED even under a module filter. Values list both project-local and
  -- external (Mathlib/Init/Std) imports. Computed from the env header — no parse.
  let mut moduleImports : Array (String × Json) := #[]
  for i in [:mods.size] do
    if mods[i]!.getRoot == rootName then
      projectModules := projectModules.push (.str mods[i]!.toString)
      let imps := env.header.moduleData[i]!.imports.map (·.module.toString)
      moduleImports := moduleImports.push (mods[i]!.toString, .arr (imps.map .str))

  let output := Json.mkObj [
    ("root_module", .str rootModuleStr),
    ("declaration_count", .num decls.size),
    ("declarations", .arr decls),
    ("project_modules", .arr projectModules),
    ("module_imports", Json.mkObj moduleImports.toList),
    ("module_opens", Json.mkObj moduleOpens.toList),
    ("module_notations", Json.mkObj moduleNotations.toList),
    ("module_variables", Json.mkObj moduleVariables.toList),
    ("module_context", Json.mkObj moduleContext.toList)
  ]

  IO.println output.pretty
