/-
  Export all project declarations with their type signatures, fields,
  and constructors as JSON.

  Usage:
    lake build  -- must build first
    lake env lean --run <path>/ExportSigs.lean <RootModule>

  Output: JSON with declaration name, kind, module, pretty-printed type
  signature, type-level dependencies, structure fields, and inductive
  constructors.

  Only follows project-local dependencies. External library declarations
  (Mathlib/Init/Std) are excluded from deps.

  Auto-generated sub-declarations are skipped from rendered signature context;
  duplicate declarations observed through multiple modules are emitted once.
-/
import Lean

open Lean Meta

/-- Classify a constant into a user-facing kind, or `none` for internal things. -/
def getKind (ci : ConstantInfo) : Option String := match ci with
  | .ctorInfo _  => none
  | .recInfo _   => none
  | .quotInfo _  => none
  | .defnInfo _  => some "def"
  | .thmInfo _   => some "theorem"
  | .axiomInfo _  => some "axiom"
  | .inductInfo _ => some "inductive"
  | .opaqueInfo _ => some "opaque"

/-- Get constants referenced only in the TYPE of a declaration. -/
def getTypeConstants (ci : ConstantInfo) : Array Name :=
  ci.type.getUsedConstants

/-- Get constants referenced in the VALUE of a declaration. -/
def getValueConstants (ci : ConstantInfo) : Array Name := match ci with
  | .defnInfo v  => v.value.getUsedConstants
  | .thmInfo v   => v.value.getUsedConstants
  | .opaqueInfo v => v.value.getUsedConstants
  | _ => #[]

/-- Get all constants (type + value). -/
def getAllConstants (ci : ConstantInfo) : Array Name :=
  getTypeConstants ci ++ getValueConstants ci

/-- Find the parent name for a sub-declaration by stripping the last component. -/
def findParent (name : Name) (projectNames : NameHashSet) : Option Name :=
  match name with
  | .str parent _ =>
    if projectNames.contains parent then some parent else none
  | _ => none

/-- Check if a name looks like a compiler-generated proof sub-declaration
    (e.g., `Foo.bar._proof_1`, `Foo.bar._uniq.123`). -/
def isProofSubDecl (name : Name) : Bool :=
  match name with
  | .str _ s => s.startsWith "_proof_" || s.startsWith "_uniq."
  | .num (.str _ s) _ => s == "_uniq"
  | _ => false

/-- Auto-generated boilerplate suffixes that Lean creates for structures/inductives.
    These are not useful for auditors. -/
private def autoGenSuffixes : Array String :=
  #["noConfusion", "noConfusionType", "recOn", "casesOn", "ctorIdx",
    "brecOn", "sizeOf_spec", "congr_simp"]

/-- Check if a name is auto-generated boilerplate for a structure/inductive.
    E.g., `Foo.Bar.noConfusion`, `Foo.Bar.mk.injEq`, `Foo.Bar.mk.sizeOf_spec`. -/
def isAutoGenerated (name : Name) (projectNames : NameHashSet) : Bool :=
  match name with
  | .str parent s =>
    -- Direct suffix match (e.g., Foo.Bar.noConfusion)
    if autoGenSuffixes.contains s then true
    -- .mk sub-declarations (e.g., Foo.Bar.mk.injEq, Foo.Bar.mk.inj)
    else match parent with
    | .str grandparent "mk" => projectNames.contains grandparent
    | _ => false
  | _ => false

/-- Get the head constant name from an expression, stripping applications
    and projections. E.g., `(eigenvaluesOf_spec ρ).2.2.2` → `eigenvaluesOf_spec`. -/
partial def getHeadConst : Expr → Option Name
  | .app f _ => getHeadConst f
  | .proj _ _ e => getHeadConst e
  | .const n _ => some n
  | .mdata _ e => getHeadConst e
  | _ => none

/-- Get the head function constant from an application spine.
    `f a1 a2 ... aN` → `f` (if `f` is a const). Strips projections too. -/
partial def getAppHeadConst : Expr → Option Name
  | .app f _ => getAppHeadConst f
  | .const n _ => some n
  | .mdata _ e => getAppHeadConst e
  | .proj _ _ e => getAppHeadConst e
  | _ => none

/-- Collect all constant names from an expression, recursively.
    Uses fuel to avoid blowup on large expressions. -/
partial def collectAllConsts (e : Expr) (fuel : Nat := 50) : Array Name :=
  if fuel == 0 then #[]
  else match e with
    | .const n _ => #[n]
    | .app f a => collectAllConsts f (fuel - 1) ++ collectAllConsts a (fuel - 1)
    | .proj _ _ inner => collectAllConsts inner (fuel - 1)
    | .lam _ t b _ => collectAllConsts t (fuel - 1) ++ collectAllConsts b (fuel - 1)
    | .forallE _ t b _ => collectAllConsts t (fuel - 1) ++ collectAllConsts b (fuel - 1)
    | .letE _ t v b _ => collectAllConsts t (fuel - 1) ++ collectAllConsts v (fuel - 1)
                          ++ collectAllConsts b (fuel - 1)
    | .mdata _ inner => collectAllConsts inner (fuel - 1)
    | _ => #[]

/-- Resolve a `_proof_N` sub-declaration to the most informative
    constant in its value. Returns `none` if resolution fails. -/
def resolveProofSubDecl (env : Environment) (name : Name)
    (projectNames : NameHashSet) : Option Name := do
  if !isProofSubDecl name then failure
  let ci ← env.find? name
  let val ← match ci with
    | .thmInfo v => some v.value
    | .defnInfo v => some v.value
    | _ => none
  -- Strip lambdas to get to the body
  let mut e := val
  while e.isLambda do
    e := e.bindingBody!
  let consts := collectAllConsts e
  -- Prefer project-local, non-internal, non-proof-subdecl names
  for c in consts do
    if projectNames.contains c && c != name && !isProofSubDecl c && !c.isInternal then
      return c
  failure

/-- Replace references to `_proof_N` sub-declarations with the resolved head constant
    in an expression. This makes pretty-printed output show the original theorem names. -/
partial def resolveProofRefs (env : Environment) (projectNames : NameHashSet)
    (e : Expr) : Expr :=
  match e with
  | .const n ls =>
    match resolveProofSubDecl env n projectNames with
    | some resolved => .const resolved ls
    | none => e
  | .app f a => .app (resolveProofRefs env projectNames f)
                     (resolveProofRefs env projectNames a)
  | .lam n t b bi => .lam n (resolveProofRefs env projectNames t)
                            (resolveProofRefs env projectNames b) bi
  | .forallE n t b bi => .forallE n (resolveProofRefs env projectNames t)
                                    (resolveProofRefs env projectNames b) bi
  | .letE n t v b nd => .letE n (resolveProofRefs env projectNames t)
                                (resolveProofRefs env projectNames v)
                                (resolveProofRefs env projectNames b) nd
  | .mdata m e => .mdata m (resolveProofRefs env projectNames e)
  | .proj t i e => .proj t i (resolveProofRefs env projectNames e)
  | _ => e

/-- Run a MetaM action in IO with the given environment. -/
def runMetaIO (env : Environment) (action : MetaM α) : IO (Except Exception α) := do
  let opts := ({} : Options)
    |>.setBool `pp.fieldNotation true
    |>.setBool `pp.fullNames false
    |>.setBool `pp.proofs false
    |>.setBool `pp.universes false
    |>.setBool `pp.instanceNames false
    |>.setBool `pp.all false
    |>.setBool `pp.raw false
  let coreCtx : Core.Context := {
    options := opts
    fileName := "<export>"
    fileMap := FileMap.ofString ""
  }
  let coreState : Core.State := { env := env }
  (action.run' {} {} |>.run' coreCtx coreState).toIO'

/-- Run a MetaM action in IO with the given environment and a set of open namespaces.
    Opening the declaration's own namespace chain allows pp.fullNames=false to shorten
    sibling references (e.g. `Foo.Bar.Baz` → `Baz` when `Foo.Bar` is open). -/
def runMetaIOWithOpenDecls (env : Environment) (openDecls : List OpenDecl)
    (action : MetaM α) : IO (Except Exception α) := do
  let opts := ({} : Options)
    |>.setBool `pp.fieldNotation true
    |>.setBool `pp.fullNames false
    |>.setBool `pp.proofs false
    |>.setBool `pp.universes false
    |>.setBool `pp.instanceNames false
    |>.setBool `pp.all false
    |>.setBool `pp.raw false
  let coreCtx : Core.Context := {
    options := opts
    fileName := "<export>"
    fileMap := FileMap.ofString ""
    openDecls := openDecls
  }
  let coreState : Core.State := { env := env }
  (action.run' {} {} |>.run' coreCtx coreState).toIO'

/-- Build the list of OpenDecl entries for all namespace prefixes of a declaration name.
    For `A.B.C.myDef` this opens `A`, `A.B`, and `A.B.C`, matching what Lean does when
    the declaration is written inside `namespace A.B.C`. Skips `.anonymous`. -/
def namespacesOf (declName : Name) : List OpenDecl :=
  let rec go (n : Name) (acc : List OpenDecl) : List OpenDecl :=
    match n with
    | .anonymous => acc
    | .str .anonymous _ => acc  -- top-level name; no namespace to open
    | .str parent _ => go parent (.simple parent [] :: acc)
    | .num parent _ => go parent acc
  go declName []

/-- Pretty-print an expression using Lean's formatter. -/
def ppExprStr (env : Environment) (e : Expr) : IO String := do
  match ← runMetaIO env (do return (← ppExpr e).pretty (width := 120)) with
  | .ok result => return result
  | .error e => return s!"<pp error: {← e.toMessageData.toString}>"

/-- Pretty-print an expression with the declaration's own namespace chain opened,
    plus any additional open decls (e.g., project-wide namespaces).
    This shortens references to siblings and cross-module project types. -/
def ppExprStrIn (env : Environment) (declName : Name) (e : Expr)
    (extraOpenDecls : List OpenDecl := []) : IO String := do
  let opens := namespacesOf declName ++ extraOpenDecls
  match ← runMetaIOWithOpenDecls env opens (do return (← ppExpr e).pretty (width := 120)) with
  | .ok result => return result
  | .error e => return s!"<pp error: {← e.toMessageData.toString}>"

/-- Check if a constant name transitively contains `sorryAx` in its value,
    following `_proof_N` sub-declaration references. -/
partial def isSorryTaintedConst (env : Environment) (name : Name) : Bool :=
  go name {}  |>.2
where
  go (name : Name) (visited : NameHashSet) : NameHashSet × Bool :=
    if visited.contains name then (visited, false)
    else
      let visited := visited.insert name
      match env.find? name with
      | none => (visited, false)
      | some ci =>
        let val? := match ci with
          | .thmInfo v => some v.value
          | .defnInfo v => some v.value
          | .opaqueInfo v => some v.value
          | _ => none
        match val? with
        | none => (visited, false)
        | some val =>
          if val.getUsedConstants.any (· == ``sorryAx) then (visited, true)
          else
            let subProofs := val.getUsedConstants.filter fun n =>
              match n with
              | .str _ s => s.startsWith "_proof_" || s.startsWith "_uniq."
              | _ => false
            subProofs.foldl (init := (visited, false)) fun (vis, found) sp =>
              if found then (vis, true)
              else go sp vis

/-- Compute the set of constant names referenced by `root` that transitively
    contain `sorryAx`. Only checks `_proof_N` / `_uniq` sub-declarations. -/
def computeSorryTainted (env : Environment) (root : Expr) : NameHashSet :=
  let directRefs := root.getUsedConstants
  let candidates := directRefs.filter fun n =>
    match n with
    | .str _ s => s.startsWith "_proof_" || s.startsWith "_uniq."
    | _ => false
  candidates.foldl (init := {}) fun tainted c =>
    if isSorryTaintedConst env c then tainted.insert c else tainted

/-- Check if a declaration's value transitively contains `sorryAx`,
    following `_proof_N` references. -/
def hasSorryTransitiveCheck (env : Environment) (ci : ConstantInfo) : Bool :=
  let val? := match ci with
    | .thmInfo v => some v.value
    | .defnInfo v => some v.value
    | .opaqueInfo v => some v.value
    | _ => none
  match val? with
  | none => false
  | some val =>
    if val.getUsedConstants.any (· == ``sorryAx) then true
    else !(computeSorryTainted env val).isEmpty

/-- Erase Prop-typed subexpressions in a value, replacing them with `⋯`.
    This hides proof terms while preserving computational content.
    Works on the Expr level before pretty-printing.

    Key design: when erasing a Prop-typed argument, we don't replace it
    entirely with sorry. Instead we "shallow erase": preserve the head
    constant/theorem name but erase ITS Prop-typed arguments. This way
    `Classical.choose (exists_unique_threshold h1 h2)` becomes
    `Classical.choose (exists_unique_threshold ⋯ ⋯)` rather than
    `Classical.choose ⋯`, keeping the semantic link to the theorem name.

    When a Prop-typed expression's head constant is in the sorry-tainted set,
    we replace the entire expression with `sorryAx` so that `pp.proofs false`
    renders it as `sorry`. -/
partial def erasePropSubexprs (env : Environment) (e : Expr)
    (sorryTainted : NameHashSet := {}) : IO Expr := do
  match ← runMetaIO env (erasePropsM e) with
  | .ok result => return result
  | .error _ => return e  -- fallback: return original
where
  /-- Check if any constant in the expression is in the sorry-tainted set. -/
  containsSorryTainted (e : Expr) : Bool :=
    e.getUsedConstants.any sorryTainted.contains

  /-- Shallow-erase a Prop-typed expression: keep its head constant name
      but replace all its Prop-typed arguments with ⋯.
      Non-Prop arguments are kept as-is (they carry type info).
      If any constant is sorry-tainted, replace the whole thing with sorryAx
      so pp renders it as `sorry`. -/
  shallowEraseProp (e : Expr) : MetaM Expr := do
    if containsSorryTainted e then
      return mkConst ``sorryAx
    match e with
    | .app f a =>
      let f' ← shallowEraseProp f
      let aType? ← try some <$> inferType a catch _ => pure none
      match aType? with
      | some aType =>
        let isPropArg ← try isProp aType catch _ => pure false
        if isPropArg then
          return .app f' (.const `«⋯» [])
        else
          return .app f' a
      | none => return .app f' a
    | .proj typeName idx struct =>
      -- Preserve projections — recurse into the struct to keep its head name
      let struct' ← shallowEraseProp struct
      return .proj typeName idx struct'
    | .mdata m e => return .mdata m (← shallowEraseProp e)
    | _ => return e  -- base case: keep constants, vars, etc.

  erasePropsM (e : Expr) : MetaM Expr := do
    -- Top-level check: if the entire expression is Prop-typed, replace with ⋯
    let eType? ← try some <$> inferType e catch _ => pure none
    match eType? with
    | some eType =>
      let isFullyProp ← try isProp eType catch _ => pure false
      if isFullyProp then
        return .const `«⋯» []
    | none => pure ()
    match e with
    | .lam n t b bi =>
      let t' ← erasePropsM t
      let b' ← withLocalDecl n bi t' fun x => do
        let b' ← erasePropsM (b.instantiate1 x)
        mkLambdaFVars #[x] b'
      return b'
    | .forallE n t b bi =>
      let t' ← erasePropsM t
      let b' ← withLocalDecl n bi t' fun x => do
        let b' ← erasePropsM (b.instantiate1 x)
        mkForallFVars #[x] b'
      return b'
    | .letE n t v b _ =>
      let isProp ← try isProp t catch _ => pure false
      if isProp then
        return .letE n t (.const `«⋯» []) b true
      else
        let t' ← erasePropsM t
        let v' ← erasePropsM v
        let b' ← withLetDecl n t' v' fun x => do
          let b' ← erasePropsM (b.instantiate1 x)
          mkLetFVars #[x] b'
        return b'
    | .app f a =>
      let aType? ← try some <$> inferType a catch _ => pure none
      match aType? with
      | some aType =>
        let isPropArg ← try isProp aType catch _ => pure false
        if isPropArg then
          let f' ← erasePropsM f
          return .app f' (.const `«⋯» [])
        else
          let f' ← erasePropsM f
          let a' ← erasePropsM a
          return .app f' a'
      | none =>
        let f' ← erasePropsM f
        let a' ← erasePropsM a
        return .app f' a'
    | .mdata m e => return .mdata m (← erasePropsM e)
    | .proj t i e => return .proj t i (← erasePropsM e)
    | _ => return e

/-- Get constants from an expression, excluding those inside Prop-typed subexprs,
    with _proof_N references resolved to original theorem names. -/
def getNonPropConstants (env : Environment) (projectNames : NameHashSet)
    (e : Expr) : IO (Array Name) := do
  let tainted := computeSorryTainted env e
  let erased ← erasePropSubexprs env e tainted
  let resolved := resolveProofRefs env projectNames erased
  return resolved.getUsedConstants

/-- Replace all applications of `_proof_N` sub-declarations with `⋯`.
    These are proof terms extracted by the kernel; their pp output is
    always noise (and often garbled when `pp.proofs false` fails on them). -/
partial def eraseProofSubDeclApps (e : Expr) : Expr :=
  match e with
  | .app f a =>
    -- Check if the head of this application chain is a _proof_N constant
    let head := e.getAppFn
    match head with
    | .const n _ =>
      if isProofSubDecl n then .const `«⋯» []
      else .app (eraseProofSubDeclApps f) (eraseProofSubDeclApps a)
    | _ => .app (eraseProofSubDeclApps f) (eraseProofSubDeclApps a)
  | .lam n t b bi => .lam n (eraseProofSubDeclApps t) (eraseProofSubDeclApps b) bi
  | .forallE n t b bi => .forallE n (eraseProofSubDeclApps t) (eraseProofSubDeclApps b) bi
  | .letE n t v b nd => .letE n (eraseProofSubDeclApps t) (eraseProofSubDeclApps v) (eraseProofSubDeclApps b) nd
  | .mdata m e => .mdata m (eraseProofSubDeclApps e)
  | .proj t i e => .proj t i (eraseProofSubDeclApps e)
  | .const n _ls => if isProofSubDecl n then .const `«⋯» [] else e
  | _ => e

def ppValueStr (env : Environment) (projectNames : NameHashSet) (declName : Name)
    (e : Expr) (extraOpenDecls : List OpenDecl := []) : IO String := do
  let tainted := computeSorryTainted env e
  let cleaned := eraseProofSubDeclApps e
  let erased ← erasePropSubexprs env cleaned tainted
  let resolved := resolveProofRefs env projectNames erased
  ppExprStrIn env declName resolved extraOpenDecls

/-- Pretty-print the field type from a projection function type.
    Strips exactly `numToStrip` leading ∀/Π binders (structure type params + self)
    using forallBoundedTelescope, preserving remaining binders (e.g., ∀ x, ...).
    Opens the structure's namespace chain for shorter sibling references. -/
def ppFieldType (env : Environment) (structName : Name) (numToStrip : Nat)
    (projType : Expr) (extraOpenDecls : List OpenDecl := []) : IO String := do
  let opens := namespacesOf structName ++ extraOpenDecls
  match ← runMetaIOWithOpenDecls env opens (do
    forallBoundedTelescope projType (some numToStrip) fun _ body => do
      return (← ppExpr body).pretty (width := 120)
  ) with
  | .ok result => return result
  | .error _ => ppExprStrIn env structName projType extraOpenDecls  -- fallback to full type

/-- Get structure field info as JSON array. Returns `none` for non-structures.
    Iterates `fieldNames` (declaration order) rather than `fieldInfo` (alphabetical). -/
def getStructureFields (env : Environment) (name : Name)
    (extraOpenDecls : List OpenDecl := []) : IO (Option (Array Json)) := do
  let some info := getStructureInfo? env name | return none
  -- Get numParams from the inductive type — strip these + 1 (self) from projection types
  let numParams := match env.find? name with
    | some (.inductInfo val) => val.numParams
    | _ => 0
  let numToStrip := numParams + 1
  let mut fields : Array Json := #[]
  -- Iterate fieldNames (position order, not alphabetical fieldInfo order)
  for fieldName in info.fieldNames do
    let projName := name ++ fieldName
    let some projInfo := env.find? projName | continue
    -- Look up metadata for fromParent check
    let fromParent := match info.fieldInfo.find? (fun fi => fi.fieldName == fieldName) with
      | some fi => fi.subobject?.isSome
      | none => false
    -- Strip only structure params + self, preserving field-level binders
    let typeStr ← ppFieldType env name numToStrip projInfo.type extraOpenDecls
    fields := fields.push <| Json.mkObj [
      ("name", .str fieldName.toString),
      ("type", .str typeStr),
      ("projName", .str projName.toString),
      ("fromParent", .bool fromParent)
    ]
  return some fields

/-- Get parent structure names for structures using `extends`. Returns `none` for non-structures
    or structures with no parents. -/
def getStructureParentNames (env : Environment) (name : Name) : Option (Array Json) :=
  match getStructureInfo? env name with
  | some info =>
    if info.parentInfo.isEmpty then none
    else some (info.parentInfo.map fun p => Json.str p.structName.toString)
  | none => none

/-- Get inductive constructor info as JSON array. -/
def getConstructors (env : Environment) (name : Name)
    (extraOpenDecls : List OpenDecl := []) : IO (Option (Array Json)) := do
  let some indInfo := env.find? name | return none
  let .inductInfo val := indInfo | return none
  let mut ctors : Array Json := #[]
  for ctorName in val.ctors do
    let some ctorInfo := env.find? ctorName | continue
    -- Open the inductive's namespace so constructor types show short sibling names
    let typeStr ← ppExprStrIn env name ctorInfo.type extraOpenDecls
    ctors := ctors.push <| Json.mkObj [
      ("name", .str (ctorName.getString!)),
      ("type", .str typeStr)
    ]
  return some ctors

/-- Get field-level type dependencies for structures (constants in field types). -/
def getFieldTypeDeps (env : Environment) (name : Name) : Array Name :=
  match getStructureInfo? env name with
  | none => #[]
  | some info =>
    info.fieldInfo.foldl (init := #[]) fun acc field =>
      let projName := name ++ field.fieldName
      match env.find? projName with
      | none => acc
      | some projInfo => acc ++ projInfo.type.getUsedConstants

/-- Get constructor-level type dependencies for inductives. -/
def getCtorTypeDeps (env : Environment) (name : Name) : Array Name :=
  match env.find? name with
  | none => #[]
  | some ci =>
    match ci with
    | .inductInfo val =>
      val.ctors.foldl (init := #[]) fun acc ctorName =>
        match env.find? ctorName with
        | none => acc
        | some ctorInfo => acc ++ ctorInfo.type.getUsedConstants
    | _ => #[]

unsafe def main : List String → IO Unit := fun args => do
  let rootModuleStr ← match args.head? with
    | some m => pure m
    | none =>
      IO.eprintln "Usage: lake env lean --run ExportSigs.lean <RootModule>"
      IO.Process.exit 1

  let rootModule := rootModuleStr.toName

  enableInitializersExecution
  initSearchPath (← findSysroot)
  -- loadExts := true is required so that PersistentEnvExtension states (including
  -- @[app_unexpander] registrations) are populated by calling each extension's
  -- addImportedFn. Without this, ppExpr cannot find unexpanders for notations like
  -- `^`, `*`, `≤`, `→ₗ[R]` and falls back to showing HPow.hPow, HMul.hMul, etc.
  let env ← importModules #[{ module := rootModule }] {} (loadExts := true)

  let mods := env.header.moduleNames
  let rootName := rootModule.getRoot

  -- Collect all project declaration names and namespaces
  let mut projectNames : NameHashSet := {}
  let mut projectNamespaces : NameHashSet := {}
  for i in [:mods.size] do
    if mods[i]!.getRoot != rootName then continue
    -- Add module name itself as a namespace to open
    projectNamespaces := projectNamespaces.insert mods[i]!
    let md := env.header.moduleData[i]!
    for j in [:md.constNames.size] do
      projectNames := projectNames.insert md.constNames[j]!
      -- Also add all parent namespaces of each declaration
      let mut ns := md.constNames[j]!
      while true do
        match ns with
        | .str parent _ =>
          if parent != .anonymous then
            projectNamespaces := projectNamespaces.insert parent
          ns := parent
        | _ => break

  -- Global open decls: open all project namespaces for shorter cross-module names
  let mut globalOpenDecls : List OpenDecl := []
  for ns in projectNamespaces.toList do
    globalOpenDecls := .simple ns [] :: globalOpenDecls

  -- Build class name lookup (classExtension.getState doesn't merge imports)
  let mut classNames : NameHashSet := {}
  for i in [:mods.size] do
    for e in classExtension.getModuleEntries env i do
      classNames := classNames.insert e.name

  -- Build instance name lookup (instanceExtension.getState doesn't merge imports)
  let mut instanceNames : NameHashSet := {}
  for i in [:mods.size] do
    for e in instanceExtension.ext.getModuleEntries env i do
      match e with
      | .global entry | .scoped _ entry =>
        if let some gn := entry.globalName? then
          instanceNames := instanceNames.insert gn

  -- Helper: collect deps for a declaration (type + prop-erased value + fields + ctors)
  let collectDeps := fun (name : Name) (cinfo : ConstantInfo) => do
    -- Type signature deps
    let mut allConsts := getTypeConstants cinfo
    -- Value deps (with Prop subexprs erased, so proof deps are excluded)
    match cinfo with
    | .defnInfo v =>
      let valueDeps ← getNonPropConstants env projectNames v.value
      allConsts := allConsts ++ valueDeps
    | _ => pure ()
    -- For structures: add field type deps
    allConsts := allConsts ++ getFieldTypeDeps env name
    -- For inductives: add constructor type deps
    allConsts := allConsts ++ getCtorTypeDeps env name

    let mut seen : NameHashSet := {}
    let mut projectDeps : Array String := #[]
    for c in allConsts do
      if c == name then continue
      if !projectNames.contains c then continue
      if seen.contains c then continue
      if c.isInternalDetail && (findParent c projectNames).isSome then continue
      -- Keep all project deps (not just sorry ones — we want full type context)
      seen := seen.insert c
      projectDeps := projectDeps.push c.toString
    pure projectDeps

  -- Build JSON
  let mut decls : Array Json := #[]
  let mut emittedNames : NameHashSet := {}

  for i in [:mods.size] do
    if mods[i]!.getRoot != rootName then continue
    let md := env.header.moduleData[i]!
    let modStr := mods[i]!.toString

    for j in [:md.constNames.size] do
      let name := md.constNames[j]!
      if emittedNames.contains name then continue
      emittedNames := emittedNames.insert name

      -- Skip auto-generated sub-declarations from rendered signature context.
      if name.isInternalDetail then
        if (declRangeExt.find? env name).isNone then
          if (findParent name projectNames).isSome then continue

      -- Skip auto-generated boilerplate (noConfusion, recOn, casesOn, etc.)
      if isAutoGenerated name projectNames then continue

      let some cinfo := env.find? name | continue
      let some kind := getKind cinfo | continue

      let isPrivate := name.isInternal

      -- Pretty-print the type signature with project namespaces open
      let typeStr ← ppExprStrIn env name cinfo.type globalOpenDecls

      -- Collect project deps (type + prop-erased value + fields + ctors)
      let deps ← collectDeps name cinfo

      -- Line number
      let lineNum : Option Nat := match declRangeExt.find? env name with
        | some range => some (range.range.pos.line + 1)
        | none => none

      -- Structure fields
      let fieldsJson ← getStructureFields env name globalOpenDecls

      -- Inductive constructors
      let ctorsJson ← getConstructors env name globalOpenDecls

      -- Check if this is an abbrev (unfoldable def)
      let isAbbrev := match cinfo with
        | .defnInfo v => v.hints.isAbbrev
        | _ => false

      -- Sorry check: transitive through _proof_N sub-declarations
      let hasSorry := hasSorryTransitiveCheck env cinfo

      -- Pretty-print the value (prop-erased for defs, raw for abbrevs)
      -- For sorry-containing defs, keep proofs visible so sorry locations are shown
      let valueStr ← match cinfo with
        | .defnInfo v =>
          if isAbbrev then
            let s ← ppExprStrIn env name v.value globalOpenDecls
            pure (some s)
          else
            let s ← ppValueStr env projectNames name v.value globalOpenDecls
            pure (some s)
        | _ => pure none

      -- Refine kind: distinguish structure/class/instance from plain inductive/def
      let refinedKind :=
        if isAbbrev then "abbrev"
        else if kind == "inductive" then
          if classNames.contains name then "class"
          else if (getStructureInfo? env name).isSome then "structure"
          else kind
        else if kind == "def" && instanceNames.contains name then "instance"
        else kind

      let mut jsonFields : Array (String × Json) := #[
        ("name", .str name.toString),
        ("kind", .str refinedKind),
        ("module", .str modStr),
        ("is_private", .bool isPrivate),
        ("type_signature", .str typeStr),
        ("deps", .arr (deps.map .str))
      ]

      if hasSorry then
        jsonFields := jsonFields.push ("has_sorry", .bool true)

      match lineNum with
      | some l => jsonFields := jsonFields.push ("line", .num l)
      | none => pure ()

      match fieldsJson with
      | some fs => jsonFields := jsonFields.push ("fields", .arr fs)
      | none => pure ()

      match ctorsJson with
      | some cs => jsonFields := jsonFields.push ("constructors", .arr cs)
      | none => pure ()

      -- Structure parent names (from `extends`)
      match getStructureParentNames env name with
      | some ps => jsonFields := jsonFields.push ("parents", .arr ps)
      | none => pure ()

      match valueStr with
      | some v => jsonFields := jsonFields.push ("value", .str v)
      | none => pure ()

      -- Docstring
      match ← findDocString? env name with
      | some doc => jsonFields := jsonFields.push ("docstring", .str doc)
      | none => pure ()

      decls := decls.push <| Json.mkObj jsonFields.toList

  let output := Json.mkObj [
    ("root_module", .str rootModuleStr),
    ("declaration_count", .num decls.size),
    ("declarations", .arr decls)
  ]

  IO.println output.pretty
